/* Click.c generated by valac 0.34.9, the Vala compiler
 * generated from Click.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>


#define METRONOME_OBJECTS_TYPE_CLICK_STATE (metronome_objects_click_state_get_type ())

#define METRONOME_OBJECTS_TYPE_CLICK_INTERVAL (metronome_objects_click_interval_get_type ())

#define METRONOME_OBJECTS_TYPE_CLICK (metronome_objects_click_get_type ())
#define METRONOME_OBJECTS_CLICK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_OBJECTS_TYPE_CLICK, MetronomeObjectsClick))
#define METRONOME_OBJECTS_CLICK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_OBJECTS_TYPE_CLICK, MetronomeObjectsClickClass))
#define METRONOME_OBJECTS_IS_CLICK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_OBJECTS_TYPE_CLICK))
#define METRONOME_OBJECTS_IS_CLICK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_OBJECTS_TYPE_CLICK))
#define METRONOME_OBJECTS_CLICK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_OBJECTS_TYPE_CLICK, MetronomeObjectsClickClass))

typedef struct _MetronomeObjectsClick MetronomeObjectsClick;
typedef struct _MetronomeObjectsClickClass MetronomeObjectsClickClass;
typedef struct _MetronomeObjectsClickPrivate MetronomeObjectsClickPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _MetronomeObjectsClickStartData MetronomeObjectsClickStartData;
typedef struct _MetronomeObjectsClickDoClickData MetronomeObjectsClickDoClickData;

#define METRONOME_OBJECTS_TYPE_PRESET (metronome_objects_preset_get_type ())
#define METRONOME_OBJECTS_PRESET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_OBJECTS_TYPE_PRESET, MetronomeObjectsPreset))
#define METRONOME_OBJECTS_PRESET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_OBJECTS_TYPE_PRESET, MetronomeObjectsPresetClass))
#define METRONOME_OBJECTS_IS_PRESET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_OBJECTS_TYPE_PRESET))
#define METRONOME_OBJECTS_IS_PRESET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_OBJECTS_TYPE_PRESET))
#define METRONOME_OBJECTS_PRESET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_OBJECTS_TYPE_PRESET, MetronomeObjectsPresetClass))

typedef struct _MetronomeObjectsPreset MetronomeObjectsPreset;
typedef struct _MetronomeObjectsPresetClass MetronomeObjectsPresetClass;

typedef enum  {
	METRONOME_OBJECTS_CLICK_STATE_running,
	METRONOME_OBJECTS_CLICK_STATE_stoped
} MetronomeObjectsclick_state;

typedef enum  {
	METRONOME_OBJECTS_CLICK_INTERVAL_semibreve,
	METRONOME_OBJECTS_CLICK_INTERVAL_minim,
	METRONOME_OBJECTS_CLICK_INTERVAL_crotchet,
	METRONOME_OBJECTS_CLICK_INTERVAL_quaver
} MetronomeObjectsclick_interval;

struct _MetronomeObjectsClick {
	GObject parent_instance;
	MetronomeObjectsClickPrivate * priv;
};

struct _MetronomeObjectsClickClass {
	GObjectClass parent_class;
};

struct _MetronomeObjectsClickPrivate {
	guint click_count;
	guint beat_count;
	guint timer_uint;
	MetronomeObjectsclick_state _current_state;
	guint _current_tempo;
	guint _current_beat;
};

struct _MetronomeObjectsClickStartData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	MetronomeObjectsClick* self;
	gboolean _tmp0_;
	guint interval;
	guint _tmp1_;
	guint _tmp2_;
	guint _tmp3_;
	guint _tmp4_;
};

struct _MetronomeObjectsClickDoClickData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	MetronomeObjectsClick* self;
	guint _tmp0_;
	guint _tmp1_;
	guint _tmp2_;
	guint _tmp3_;
	guint _tmp4_;
	guint _tmp5_;
	guint _tmp6_;
	guint _tmp7_;
	guint _tmp8_;
};


static gpointer metronome_objects_click_parent_class = NULL;

GType metronome_objects_click_state_get_type (void) G_GNUC_CONST;
GType metronome_objects_click_interval_get_type (void) G_GNUC_CONST;
GType metronome_objects_click_get_type (void) G_GNUC_CONST;
#define METRONOME_OBJECTS_CLICK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), METRONOME_OBJECTS_TYPE_CLICK, MetronomeObjectsClickPrivate))
enum  {
	METRONOME_OBJECTS_CLICK_DUMMY_PROPERTY,
	METRONOME_OBJECTS_CLICK_CURRENT_STATE,
	METRONOME_OBJECTS_CLICK_CURRENT_TEMPO,
	METRONOME_OBJECTS_CLICK_CURRENT_BEAT
};
MetronomeObjectsClick* metronome_objects_click_new (void);
MetronomeObjectsClick* metronome_objects_click_construct (GType object_type);
static void metronome_objects_click_set_current_state (MetronomeObjectsClick* self, MetronomeObjectsclick_state value);
static void metronome_objects_click_start_data_free (gpointer _data);
void metronome_objects_click_start (MetronomeObjectsClick* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void metronome_objects_click_start_finish (MetronomeObjectsClick* self, GAsyncResult* _res_);
static gboolean metronome_objects_click_start_co (MetronomeObjectsClickStartData* _data_);
gboolean metronome_objects_click_is_settings_valid (MetronomeObjectsClick* self);
guint metronome_objects_click_get_current_tempo (MetronomeObjectsClick* self);
void metronome_objects_click_do_click (MetronomeObjectsClick* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void metronome_objects_click_do_click_finish (MetronomeObjectsClick* self, GAsyncResult* _res_);
static gboolean __lambda4_ (MetronomeObjectsClick* self);
MetronomeObjectsclick_state metronome_objects_click_get_current_state (MetronomeObjectsClick* self);
static gboolean ___lambda4__gsource_func (gpointer self);
void metronome_objects_click_stop (MetronomeObjectsClick* self);
static void metronome_objects_click_do_click_data_free (gpointer _data);
static gboolean metronome_objects_click_do_click_co (MetronomeObjectsClickDoClickData* _data_);
guint metronome_objects_click_get_current_beat (MetronomeObjectsClick* self);
gpointer metronome_objects_preset_ref (gpointer instance);
void metronome_objects_preset_unref (gpointer instance);
GParamSpec* metronome_objects_param_spec_preset (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void metronome_objects_value_set_preset (GValue* value, gpointer v_object);
void metronome_objects_value_take_preset (GValue* value, gpointer v_object);
gpointer metronome_objects_value_get_preset (const GValue* value);
GType metronome_objects_preset_get_type (void) G_GNUC_CONST;
void metronome_objects_click_set_preset (MetronomeObjectsClick* self, MetronomeObjectsPreset* preset);
guint metronome_objects_preset_get_tempo (MetronomeObjectsPreset* self);
void metronome_objects_click_set_current_tempo (MetronomeObjectsClick* self, guint value);
guint metronome_objects_preset_get_beat (MetronomeObjectsPreset* self);
void metronome_objects_click_set_current_beat (MetronomeObjectsClick* self, guint value);
gboolean metronome_objects_click_is_tempo_valid (MetronomeObjectsClick* self, guint new_tempo);
gboolean metronome_objects_click_is_beat_valid (MetronomeObjectsClick* self, guint new_beat);
static void g_cclosure_user_marshal_VOID__ENUM_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void metronome_objects_click_finalize (GObject* obj);
static void _vala_metronome_objects_click_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_metronome_objects_click_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GType metronome_objects_click_state_get_type (void) {
	static volatile gsize metronome_objects_click_state_type_id__volatile = 0;
	if (g_once_init_enter (&metronome_objects_click_state_type_id__volatile)) {
		static const GEnumValue values[] = {{METRONOME_OBJECTS_CLICK_STATE_running, "METRONOME_OBJECTS_CLICK_STATE_running", "running"}, {METRONOME_OBJECTS_CLICK_STATE_stoped, "METRONOME_OBJECTS_CLICK_STATE_stoped", "stoped"}, {0, NULL, NULL}};
		GType metronome_objects_click_state_type_id;
		metronome_objects_click_state_type_id = g_enum_register_static ("MetronomeObjectsclick_state", values);
		g_once_init_leave (&metronome_objects_click_state_type_id__volatile, metronome_objects_click_state_type_id);
	}
	return metronome_objects_click_state_type_id__volatile;
}


GType metronome_objects_click_interval_get_type (void) {
	static volatile gsize metronome_objects_click_interval_type_id__volatile = 0;
	if (g_once_init_enter (&metronome_objects_click_interval_type_id__volatile)) {
		static const GEnumValue values[] = {{METRONOME_OBJECTS_CLICK_INTERVAL_semibreve, "METRONOME_OBJECTS_CLICK_INTERVAL_semibreve", "semibreve"}, {METRONOME_OBJECTS_CLICK_INTERVAL_minim, "METRONOME_OBJECTS_CLICK_INTERVAL_minim", "minim"}, {METRONOME_OBJECTS_CLICK_INTERVAL_crotchet, "METRONOME_OBJECTS_CLICK_INTERVAL_crotchet", "crotchet"}, {METRONOME_OBJECTS_CLICK_INTERVAL_quaver, "METRONOME_OBJECTS_CLICK_INTERVAL_quaver", "quaver"}, {0, NULL, NULL}};
		GType metronome_objects_click_interval_type_id;
		metronome_objects_click_interval_type_id = g_enum_register_static ("MetronomeObjectsclick_interval", values);
		g_once_init_leave (&metronome_objects_click_interval_type_id__volatile, metronome_objects_click_interval_type_id);
	}
	return metronome_objects_click_interval_type_id__volatile;
}


MetronomeObjectsClick* metronome_objects_click_construct (GType object_type) {
	MetronomeObjectsClick * self = NULL;
#line 45 "/home/artem/metronome/src/Objects/Click.vala"
	self = (MetronomeObjectsClick*) g_object_new (object_type, NULL);
#line 46 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_set_current_state (self, METRONOME_OBJECTS_CLICK_STATE_stoped);
#line 47 "/home/artem/metronome/src/Objects/Click.vala"
	self->priv->click_count = (guint) 0;
#line 48 "/home/artem/metronome/src/Objects/Click.vala"
	self->priv->beat_count = (guint) 0;
#line 45 "/home/artem/metronome/src/Objects/Click.vala"
	return self;
#line 187 "Click.c"
}


MetronomeObjectsClick* metronome_objects_click_new (void) {
#line 45 "/home/artem/metronome/src/Objects/Click.vala"
	return metronome_objects_click_construct (METRONOME_OBJECTS_TYPE_CLICK);
#line 194 "Click.c"
}


static void metronome_objects_click_start_data_free (gpointer _data) {
	MetronomeObjectsClickStartData* _data_;
	_data_ = _data;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_g_object_unref0 (_data_->self);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_slice_free (MetronomeObjectsClickStartData, _data_);
#line 205 "Click.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	return self ? g_object_ref (self) : NULL;
#line 212 "Click.c"
}


void metronome_objects_click_start (MetronomeObjectsClick* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	MetronomeObjectsClickStartData* _data_;
	MetronomeObjectsClick* _tmp0_ = NULL;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_data_ = g_slice_new0 (MetronomeObjectsClickStartData);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, metronome_objects_click_start);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, metronome_objects_click_start_data_free);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->self = _tmp0_;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_start_co (_data_);
#line 231 "Click.c"
}


void metronome_objects_click_start_finish (MetronomeObjectsClick* self, GAsyncResult* _res_) {
	MetronomeObjectsClickStartData* _data_;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 239 "Click.c"
}


static gboolean __lambda4_ (MetronomeObjectsClick* self) {
	gboolean result = FALSE;
	MetronomeObjectsclick_state _tmp0_ = 0;
	MetronomeObjectsclick_state _tmp1_ = 0;
#line 62 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = metronome_objects_click_get_current_state (self);
#line 62 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp1_ = _tmp0_;
#line 62 "/home/artem/metronome/src/Objects/Click.vala"
	if (_tmp1_ == METRONOME_OBJECTS_CLICK_STATE_stoped) {
#line 63 "/home/artem/metronome/src/Objects/Click.vala"
		result = FALSE;
#line 63 "/home/artem/metronome/src/Objects/Click.vala"
		return result;
#line 257 "Click.c"
	}
#line 65 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_do_click (self, NULL, NULL);
#line 66 "/home/artem/metronome/src/Objects/Click.vala"
	result = TRUE;
#line 66 "/home/artem/metronome/src/Objects/Click.vala"
	return result;
#line 265 "Click.c"
}


static gboolean ___lambda4__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda4_ ((MetronomeObjectsClick*) self);
#line 61 "/home/artem/metronome/src/Objects/Click.vala"
	return result;
#line 274 "Click.c"
}


static gboolean metronome_objects_click_start_co (MetronomeObjectsClickStartData* _data_) {
#line 51 "/home/artem/metronome/src/Objects/Click.vala"
	switch (_data_->_state_) {
#line 51 "/home/artem/metronome/src/Objects/Click.vala"
		case 0:
#line 283 "Click.c"
		goto _state_0;
		default:
#line 51 "/home/artem/metronome/src/Objects/Click.vala"
		g_assert_not_reached ();
#line 288 "Click.c"
	}
	_state_0:
#line 52 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp0_ = FALSE;
#line 52 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp0_ = metronome_objects_click_is_settings_valid (_data_->self);
#line 52 "/home/artem/metronome/src/Objects/Click.vala"
	if (!_data_->_tmp0_) {
#line 53 "/home/artem/metronome/src/Objects/Click.vala"
		if (_data_->_state_ == 0) {
#line 53 "/home/artem/metronome/src/Objects/Click.vala"
			g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 301 "Click.c"
		} else {
#line 53 "/home/artem/metronome/src/Objects/Click.vala"
			g_simple_async_result_complete (_data_->_async_result);
#line 305 "Click.c"
		}
#line 53 "/home/artem/metronome/src/Objects/Click.vala"
		g_object_unref (_data_->_async_result);
#line 53 "/home/artem/metronome/src/Objects/Click.vala"
		return FALSE;
#line 311 "Click.c"
	}
#line 55 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp1_ = 0U;
#line 55 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp1_ = metronome_objects_click_get_current_tempo (_data_->self);
#line 55 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp2_ = 0U;
#line 55 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp2_ = _data_->_tmp1_;
#line 55 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->interval = (60000 / _data_->_tmp2_) / 8;
#line 57 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_set_current_state (_data_->self, METRONOME_OBJECTS_CLICK_STATE_running);
#line 59 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_do_click (_data_->self, NULL, NULL);
#line 61 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp3_ = 0U;
#line 61 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp3_ = _data_->interval;
#line 61 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp4_ = 0U;
#line 61 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp4_ = g_timeout_add_full (G_PRIORITY_HIGH, _data_->_tmp3_, ___lambda4__gsource_func, g_object_ref (_data_->self), g_object_unref);
#line 61 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->self->priv->timer_uint = _data_->_tmp4_;
#line 51 "/home/artem/metronome/src/Objects/Click.vala"
	if (_data_->_state_ == 0) {
#line 51 "/home/artem/metronome/src/Objects/Click.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 341 "Click.c"
	} else {
#line 51 "/home/artem/metronome/src/Objects/Click.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 345 "Click.c"
	}
#line 51 "/home/artem/metronome/src/Objects/Click.vala"
	g_object_unref (_data_->_async_result);
#line 51 "/home/artem/metronome/src/Objects/Click.vala"
	return FALSE;
#line 351 "Click.c"
}


void metronome_objects_click_stop (MetronomeObjectsClick* self) {
	guint _tmp0_ = 0U;
#line 70 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_if_fail (self != NULL);
#line 71 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = self->priv->timer_uint;
#line 71 "/home/artem/metronome/src/Objects/Click.vala"
	if (_tmp0_ > ((guint) 0)) {
#line 363 "Click.c"
		guint _tmp1_ = 0U;
#line 72 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp1_ = self->priv->timer_uint;
#line 72 "/home/artem/metronome/src/Objects/Click.vala"
		g_source_remove (_tmp1_);
#line 73 "/home/artem/metronome/src/Objects/Click.vala"
		self->priv->timer_uint = (guint) 0;
#line 371 "Click.c"
	}
#line 75 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_set_current_state (self, METRONOME_OBJECTS_CLICK_STATE_stoped);
#line 76 "/home/artem/metronome/src/Objects/Click.vala"
	self->priv->click_count = (guint) 0;
#line 77 "/home/artem/metronome/src/Objects/Click.vala"
	self->priv->beat_count = (guint) 0;
#line 379 "Click.c"
}


static void metronome_objects_click_do_click_data_free (gpointer _data) {
	MetronomeObjectsClickDoClickData* _data_;
	_data_ = _data;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_g_object_unref0 (_data_->self);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_slice_free (MetronomeObjectsClickDoClickData, _data_);
#line 390 "Click.c"
}


void metronome_objects_click_do_click (MetronomeObjectsClick* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	MetronomeObjectsClickDoClickData* _data_;
	MetronomeObjectsClick* _tmp0_ = NULL;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_data_ = g_slice_new0 (MetronomeObjectsClickDoClickData);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, metronome_objects_click_do_click);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, metronome_objects_click_do_click_data_free);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->self = _tmp0_;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_do_click_co (_data_);
#line 409 "Click.c"
}


void metronome_objects_click_do_click_finish (MetronomeObjectsClick* self, GAsyncResult* _res_) {
	MetronomeObjectsClickDoClickData* _data_;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 417 "Click.c"
}


static gboolean metronome_objects_click_do_click_co (MetronomeObjectsClickDoClickData* _data_) {
#line 80 "/home/artem/metronome/src/Objects/Click.vala"
	switch (_data_->_state_) {
#line 80 "/home/artem/metronome/src/Objects/Click.vala"
		case 0:
#line 426 "Click.c"
		goto _state_0;
#line 80 "/home/artem/metronome/src/Objects/Click.vala"
		case 1:
#line 430 "Click.c"
		goto _state_1;
		default:
#line 80 "/home/artem/metronome/src/Objects/Click.vala"
		g_assert_not_reached ();
#line 435 "Click.c"
	}
	_state_0:
#line 81 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp0_ = 0U;
#line 81 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp0_ = _data_->self->priv->click_count;
#line 81 "/home/artem/metronome/src/Objects/Click.vala"
	if (_data_->_tmp0_ == ((guint) 0)) {
#line 82 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp1_ = 0U;
#line 82 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp1_ = _data_->self->priv->beat_count;
#line 82 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp2_ = 0U;
#line 82 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp2_ = metronome_objects_click_get_current_beat (_data_->self);
#line 82 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp3_ = 0U;
#line 82 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp3_ = _data_->_tmp2_;
#line 82 "/home/artem/metronome/src/Objects/Click.vala"
		g_signal_emit_by_name (_data_->self, "click", METRONOME_OBJECTS_CLICK_INTERVAL_semibreve, (_data_->_tmp1_ % _data_->_tmp3_) == ((guint) 0));
#line 83 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp4_ = 0U;
#line 83 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp4_ = _data_->self->priv->beat_count;
#line 83 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->self->priv->beat_count = _data_->_tmp4_ + 1;
#line 464 "Click.c"
	} else {
#line 85 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp5_ = 0U;
#line 85 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp5_ = _data_->self->priv->click_count;
#line 85 "/home/artem/metronome/src/Objects/Click.vala"
		if ((_data_->_tmp5_ % 4) == ((guint) 0)) {
#line 86 "/home/artem/metronome/src/Objects/Click.vala"
			g_signal_emit_by_name (_data_->self, "click", METRONOME_OBJECTS_CLICK_INTERVAL_minim, FALSE);
#line 474 "Click.c"
		} else {
#line 87 "/home/artem/metronome/src/Objects/Click.vala"
			_data_->_tmp6_ = 0U;
#line 87 "/home/artem/metronome/src/Objects/Click.vala"
			_data_->_tmp6_ = _data_->self->priv->click_count;
#line 87 "/home/artem/metronome/src/Objects/Click.vala"
			if ((_data_->_tmp6_ % 2) == ((guint) 0)) {
#line 88 "/home/artem/metronome/src/Objects/Click.vala"
				g_signal_emit_by_name (_data_->self, "click", METRONOME_OBJECTS_CLICK_INTERVAL_crotchet, FALSE);
#line 484 "Click.c"
			} else {
#line 90 "/home/artem/metronome/src/Objects/Click.vala"
				g_signal_emit_by_name (_data_->self, "click", METRONOME_OBJECTS_CLICK_INTERVAL_quaver, FALSE);
#line 488 "Click.c"
			}
		}
	}
#line 92 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp7_ = 0U;
#line 92 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_tmp7_ = _data_->self->priv->click_count;
#line 92 "/home/artem/metronome/src/Objects/Click.vala"
	if (_data_->_tmp7_ == ((guint) 7)) {
#line 93 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->self->priv->click_count = (guint) 0;
#line 500 "Click.c"
	} else {
#line 95 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp8_ = 0U;
#line 95 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->_tmp8_ = _data_->self->priv->click_count;
#line 95 "/home/artem/metronome/src/Objects/Click.vala"
		_data_->self->priv->click_count = _data_->_tmp8_ + 1;
#line 508 "Click.c"
	}
#line 97 "/home/artem/metronome/src/Objects/Click.vala"
	_data_->_state_ = 1;
#line 97 "/home/artem/metronome/src/Objects/Click.vala"
	return FALSE;
#line 514 "Click.c"
	_state_1:
	;
#line 80 "/home/artem/metronome/src/Objects/Click.vala"
	if (_data_->_state_ == 0) {
#line 80 "/home/artem/metronome/src/Objects/Click.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 521 "Click.c"
	} else {
#line 80 "/home/artem/metronome/src/Objects/Click.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 525 "Click.c"
	}
#line 80 "/home/artem/metronome/src/Objects/Click.vala"
	g_object_unref (_data_->_async_result);
#line 80 "/home/artem/metronome/src/Objects/Click.vala"
	return FALSE;
#line 531 "Click.c"
}


void metronome_objects_click_set_preset (MetronomeObjectsClick* self, MetronomeObjectsPreset* preset) {
	MetronomeObjectsPreset* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	MetronomeObjectsPreset* _tmp3_ = NULL;
	guint _tmp4_ = 0U;
	guint _tmp5_ = 0U;
	MetronomeObjectsclick_state _tmp6_ = 0;
	MetronomeObjectsclick_state _tmp7_ = 0;
#line 100 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_if_fail (self != NULL);
#line 100 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_if_fail (preset != NULL);
#line 101 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = preset;
#line 101 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp1_ = metronome_objects_preset_get_tempo (_tmp0_);
#line 101 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp2_ = _tmp1_;
#line 101 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_set_current_tempo (self, _tmp2_);
#line 102 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp3_ = preset;
#line 102 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp4_ = metronome_objects_preset_get_beat (_tmp3_);
#line 102 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp5_ = _tmp4_;
#line 102 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_set_current_beat (self, _tmp5_);
#line 103 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp6_ = metronome_objects_click_get_current_state (self);
#line 103 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp7_ = _tmp6_;
#line 103 "/home/artem/metronome/src/Objects/Click.vala"
	if (_tmp7_ == METRONOME_OBJECTS_CLICK_STATE_running) {
#line 104 "/home/artem/metronome/src/Objects/Click.vala"
		metronome_objects_click_stop (self);
#line 105 "/home/artem/metronome/src/Objects/Click.vala"
		metronome_objects_click_start (self, NULL, NULL);
#line 574 "Click.c"
	}
}


gboolean metronome_objects_click_is_settings_valid (MetronomeObjectsClick* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	guint _tmp1_ = 0U;
	guint _tmp2_ = 0U;
	gboolean _tmp3_ = FALSE;
#line 109 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp1_ = metronome_objects_click_get_current_tempo (self);
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp2_ = _tmp1_;
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp3_ = metronome_objects_click_is_tempo_valid (self, _tmp2_);
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
	if (_tmp3_) {
#line 595 "Click.c"
		guint _tmp4_ = 0U;
		guint _tmp5_ = 0U;
		gboolean _tmp6_ = FALSE;
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp4_ = metronome_objects_click_get_current_beat (self);
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp5_ = _tmp4_;
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp6_ = metronome_objects_click_is_beat_valid (self, _tmp5_);
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp0_ = _tmp6_;
#line 607 "Click.c"
	} else {
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp0_ = FALSE;
#line 611 "Click.c"
	}
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
	result = _tmp0_;
#line 110 "/home/artem/metronome/src/Objects/Click.vala"
	return result;
#line 617 "Click.c"
}


gboolean metronome_objects_click_is_tempo_valid (MetronomeObjectsClick* self, guint new_tempo) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	guint _tmp1_ = 0U;
#line 113 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 114 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp1_ = new_tempo;
#line 114 "/home/artem/metronome/src/Objects/Click.vala"
	if (_tmp1_ >= ((guint) 30)) {
#line 631 "Click.c"
		guint _tmp2_ = 0U;
#line 114 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp2_ = new_tempo;
#line 114 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp0_ = _tmp2_ <= ((guint) 240);
#line 637 "Click.c"
	} else {
#line 114 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp0_ = FALSE;
#line 641 "Click.c"
	}
#line 114 "/home/artem/metronome/src/Objects/Click.vala"
	result = _tmp0_;
#line 114 "/home/artem/metronome/src/Objects/Click.vala"
	return result;
#line 647 "Click.c"
}


gboolean metronome_objects_click_is_beat_valid (MetronomeObjectsClick* self, guint new_beat) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	guint _tmp1_ = 0U;
#line 117 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 118 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp1_ = new_beat;
#line 118 "/home/artem/metronome/src/Objects/Click.vala"
	if (_tmp1_ >= ((guint) 1)) {
#line 661 "Click.c"
		guint _tmp2_ = 0U;
#line 118 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp2_ = new_beat;
#line 118 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp0_ = _tmp2_ <= ((guint) 9);
#line 667 "Click.c"
	} else {
#line 118 "/home/artem/metronome/src/Objects/Click.vala"
		_tmp0_ = FALSE;
#line 671 "Click.c"
	}
#line 118 "/home/artem/metronome/src/Objects/Click.vala"
	result = _tmp0_;
#line 118 "/home/artem/metronome/src/Objects/Click.vala"
	return result;
#line 677 "Click.c"
}


MetronomeObjectsclick_state metronome_objects_click_get_current_state (MetronomeObjectsClick* self) {
	MetronomeObjectsclick_state result;
	MetronomeObjectsclick_state _tmp0_ = 0;
#line 20 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 20 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = self->priv->_current_state;
#line 20 "/home/artem/metronome/src/Objects/Click.vala"
	result = _tmp0_;
#line 20 "/home/artem/metronome/src/Objects/Click.vala"
	return result;
#line 692 "Click.c"
}


static void metronome_objects_click_set_current_state (MetronomeObjectsClick* self, MetronomeObjectsclick_state value) {
	MetronomeObjectsclick_state _tmp0_ = 0;
	MetronomeObjectsclick_state _tmp1_ = 0;
	MetronomeObjectsclick_state _tmp2_ = 0;
#line 21 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_if_fail (self != NULL);
#line 22 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = value;
#line 22 "/home/artem/metronome/src/Objects/Click.vala"
	self->priv->_current_state = _tmp0_;
#line 23 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp1_ = metronome_objects_click_get_current_state (self);
#line 23 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp2_ = _tmp1_;
#line 23 "/home/artem/metronome/src/Objects/Click.vala"
	g_signal_emit_by_name (self, "state-changed", _tmp2_);
#line 21 "/home/artem/metronome/src/Objects/Click.vala"
	g_object_notify ((GObject *) self, "current-state");
#line 714 "Click.c"
}


guint metronome_objects_click_get_current_tempo (MetronomeObjectsClick* self) {
	guint result;
	guint _tmp0_ = 0U;
#line 29 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_val_if_fail (self != NULL, 0U);
#line 29 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = self->priv->_current_tempo;
#line 29 "/home/artem/metronome/src/Objects/Click.vala"
	result = _tmp0_;
#line 29 "/home/artem/metronome/src/Objects/Click.vala"
	return result;
#line 729 "Click.c"
}


void metronome_objects_click_set_current_tempo (MetronomeObjectsClick* self, guint value) {
	guint _tmp0_ = 0U;
	guint _tmp1_ = 0U;
#line 30 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_if_fail (self != NULL);
#line 31 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = value;
#line 31 "/home/artem/metronome/src/Objects/Click.vala"
	self->priv->_current_tempo = _tmp0_;
#line 32 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp1_ = value;
#line 32 "/home/artem/metronome/src/Objects/Click.vala"
	g_signal_emit_by_name (self, "tempo-changed", _tmp1_);
#line 30 "/home/artem/metronome/src/Objects/Click.vala"
	g_object_notify ((GObject *) self, "current-tempo");
#line 748 "Click.c"
}


guint metronome_objects_click_get_current_beat (MetronomeObjectsClick* self) {
	guint result;
	guint _tmp0_ = 0U;
#line 38 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_val_if_fail (self != NULL, 0U);
#line 38 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = self->priv->_current_beat;
#line 38 "/home/artem/metronome/src/Objects/Click.vala"
	result = _tmp0_;
#line 38 "/home/artem/metronome/src/Objects/Click.vala"
	return result;
#line 763 "Click.c"
}


void metronome_objects_click_set_current_beat (MetronomeObjectsClick* self, guint value) {
	guint _tmp0_ = 0U;
	guint _tmp1_ = 0U;
#line 39 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_if_fail (self != NULL);
#line 40 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp0_ = value;
#line 40 "/home/artem/metronome/src/Objects/Click.vala"
	self->priv->_current_beat = _tmp0_;
#line 41 "/home/artem/metronome/src/Objects/Click.vala"
	_tmp1_ = value;
#line 41 "/home/artem/metronome/src/Objects/Click.vala"
	g_signal_emit_by_name (self, "beat-changed", _tmp1_);
#line 39 "/home/artem/metronome/src/Objects/Click.vala"
	g_object_notify ((GObject *) self, "current-beat");
#line 782 "Click.c"
}


static void g_cclosure_user_marshal_VOID__ENUM_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__ENUM_BOOLEAN) (gpointer data1, gint arg_1, gboolean arg_2, gpointer data2);
	register GMarshalFunc_VOID__ENUM_BOOLEAN callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_return_if_fail (n_param_values == 3);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		data1 = closure->data;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		data2 = param_values->data[0].v_pointer;
#line 801 "Click.c"
	} else {
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		data1 = param_values->data[0].v_pointer;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		data2 = closure->data;
#line 807 "Click.c"
	}
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	callback = (GMarshalFunc_VOID__ENUM_BOOLEAN) (marshal_data ? marshal_data : cc->callback);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	callback (data1, g_value_get_enum (param_values + 1), g_value_get_boolean (param_values + 2), data2);
#line 813 "Click.c"
}


static void metronome_objects_click_class_init (MetronomeObjectsClickClass * klass) {
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	metronome_objects_click_parent_class = g_type_class_peek_parent (klass);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_type_class_add_private (klass, sizeof (MetronomeObjectsClickPrivate));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_metronome_objects_click_get_property;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_metronome_objects_click_set_property;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	G_OBJECT_CLASS (klass)->finalize = metronome_objects_click_finalize;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), METRONOME_OBJECTS_CLICK_CURRENT_STATE, g_param_spec_enum ("current-state", "current-state", "current-state", METRONOME_OBJECTS_TYPE_CLICK_STATE, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), METRONOME_OBJECTS_CLICK_CURRENT_TEMPO, g_param_spec_uint ("current-tempo", "current-tempo", "current-tempo", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), METRONOME_OBJECTS_CLICK_CURRENT_BEAT, g_param_spec_uint ("current-beat", "current-beat", "current-beat", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_signal_new ("state_changed", METRONOME_OBJECTS_TYPE_CLICK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__ENUM, G_TYPE_NONE, 1, METRONOME_OBJECTS_TYPE_CLICK_STATE);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_signal_new ("tempo_changed", METRONOME_OBJECTS_TYPE_CLICK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__UINT, G_TYPE_NONE, 1, G_TYPE_UINT);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_signal_new ("beat_changed", METRONOME_OBJECTS_TYPE_CLICK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__UINT, G_TYPE_NONE, 1, G_TYPE_UINT);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	g_signal_new ("click", METRONOME_OBJECTS_TYPE_CLICK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__ENUM_BOOLEAN, G_TYPE_NONE, 2, METRONOME_OBJECTS_TYPE_CLICK_INTERVAL, G_TYPE_BOOLEAN);
#line 842 "Click.c"
}


static void metronome_objects_click_instance_init (MetronomeObjectsClick * self) {
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	self->priv = METRONOME_OBJECTS_CLICK_GET_PRIVATE (self);
#line 849 "Click.c"
}


static void metronome_objects_click_finalize (GObject* obj) {
	MetronomeObjectsClick * self;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, METRONOME_OBJECTS_TYPE_CLICK, MetronomeObjectsClick);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	G_OBJECT_CLASS (metronome_objects_click_parent_class)->finalize (obj);
#line 859 "Click.c"
}


GType metronome_objects_click_get_type (void) {
	static volatile gsize metronome_objects_click_type_id__volatile = 0;
	if (g_once_init_enter (&metronome_objects_click_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MetronomeObjectsClickClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) metronome_objects_click_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MetronomeObjectsClick), 0, (GInstanceInitFunc) metronome_objects_click_instance_init, NULL };
		GType metronome_objects_click_type_id;
		metronome_objects_click_type_id = g_type_register_static (G_TYPE_OBJECT, "MetronomeObjectsClick", &g_define_type_info, 0);
		g_once_init_leave (&metronome_objects_click_type_id__volatile, metronome_objects_click_type_id);
	}
	return metronome_objects_click_type_id__volatile;
}


static void _vala_metronome_objects_click_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MetronomeObjectsClick * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, METRONOME_OBJECTS_TYPE_CLICK, MetronomeObjectsClick);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	switch (property_id) {
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		case METRONOME_OBJECTS_CLICK_CURRENT_STATE:
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		g_value_set_enum (value, metronome_objects_click_get_current_state (self));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		break;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		case METRONOME_OBJECTS_CLICK_CURRENT_TEMPO:
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		g_value_set_uint (value, metronome_objects_click_get_current_tempo (self));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		break;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		case METRONOME_OBJECTS_CLICK_CURRENT_BEAT:
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		g_value_set_uint (value, metronome_objects_click_get_current_beat (self));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		break;
#line 898 "Click.c"
		default:
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		break;
#line 904 "Click.c"
	}
}


static void _vala_metronome_objects_click_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MetronomeObjectsClick * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, METRONOME_OBJECTS_TYPE_CLICK, MetronomeObjectsClick);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
	switch (property_id) {
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		case METRONOME_OBJECTS_CLICK_CURRENT_STATE:
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		metronome_objects_click_set_current_state (self, g_value_get_enum (value));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		break;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		case METRONOME_OBJECTS_CLICK_CURRENT_TEMPO:
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		metronome_objects_click_set_current_tempo (self, g_value_get_uint (value));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		break;
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		case METRONOME_OBJECTS_CLICK_CURRENT_BEAT:
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		metronome_objects_click_set_current_beat (self, g_value_get_uint (value));
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		break;
#line 932 "Click.c"
		default:
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 6 "/home/artem/metronome/src/Objects/Click.vala"
		break;
#line 938 "Click.c"
	}
}



