/* Presets.c generated by valac 0.34.9, the Vala compiler
 * generated from Presets.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>
#include <granite.h>


#define METRONOME_WIDGETS_TYPE_PRESETS (metronome_widgets_presets_get_type ())
#define METRONOME_WIDGETS_PRESETS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_WIDGETS_TYPE_PRESETS, MetronomeWidgetsPresets))
#define METRONOME_WIDGETS_PRESETS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_WIDGETS_TYPE_PRESETS, MetronomeWidgetsPresetsClass))
#define METRONOME_WIDGETS_IS_PRESETS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_WIDGETS_TYPE_PRESETS))
#define METRONOME_WIDGETS_IS_PRESETS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_WIDGETS_TYPE_PRESETS))
#define METRONOME_WIDGETS_PRESETS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_WIDGETS_TYPE_PRESETS, MetronomeWidgetsPresetsClass))

typedef struct _MetronomeWidgetsPresets MetronomeWidgetsPresets;
typedef struct _MetronomeWidgetsPresetsClass MetronomeWidgetsPresetsClass;
typedef struct _MetronomeWidgetsPresetsPrivate MetronomeWidgetsPresetsPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;

#define METRONOME_OBJECTS_TYPE_PRESET (metronome_objects_preset_get_type ())
#define METRONOME_OBJECTS_PRESET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_OBJECTS_TYPE_PRESET, MetronomeObjectsPreset))
#define METRONOME_OBJECTS_PRESET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_OBJECTS_TYPE_PRESET, MetronomeObjectsPresetClass))
#define METRONOME_OBJECTS_IS_PRESET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_OBJECTS_TYPE_PRESET))
#define METRONOME_OBJECTS_IS_PRESET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_OBJECTS_TYPE_PRESET))
#define METRONOME_OBJECTS_PRESET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_OBJECTS_TYPE_PRESET, MetronomeObjectsPresetClass))

typedef struct _MetronomeObjectsPreset MetronomeObjectsPreset;
typedef struct _MetronomeObjectsPresetClass MetronomeObjectsPresetClass;

#define METRONOME_WIDGETS_TYPE_PRESET_ROW (metronome_widgets_preset_row_get_type ())
#define METRONOME_WIDGETS_PRESET_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRow))
#define METRONOME_WIDGETS_PRESET_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRowClass))
#define METRONOME_WIDGETS_IS_PRESET_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_WIDGETS_TYPE_PRESET_ROW))
#define METRONOME_WIDGETS_IS_PRESET_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_WIDGETS_TYPE_PRESET_ROW))
#define METRONOME_WIDGETS_PRESET_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRowClass))

typedef struct _MetronomeWidgetsPresetRow MetronomeWidgetsPresetRow;
typedef struct _MetronomeWidgetsPresetRowClass MetronomeWidgetsPresetRowClass;
#define _metronome_objects_preset_unref0(var) ((var == NULL) ? NULL : (var = (metronome_objects_preset_unref (var), NULL)))

#define METRONOME_TYPE_METRONOME_APP (metronome_metronome_app_get_type ())
#define METRONOME_METRONOME_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_TYPE_METRONOME_APP, MetronomeMetronomeApp))
#define METRONOME_METRONOME_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_TYPE_METRONOME_APP, MetronomeMetronomeAppClass))
#define METRONOME_IS_METRONOME_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_TYPE_METRONOME_APP))
#define METRONOME_IS_METRONOME_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_TYPE_METRONOME_APP))
#define METRONOME_METRONOME_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_TYPE_METRONOME_APP, MetronomeMetronomeAppClass))

typedef struct _MetronomeMetronomeApp MetronomeMetronomeApp;
typedef struct _MetronomeMetronomeAppClass MetronomeMetronomeAppClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _g_array_unref0(var) ((var == NULL) ? NULL : (var = (g_array_unref (var), NULL)))

struct _MetronomeWidgetsPresets {
	GtkBox parent_instance;
	MetronomeWidgetsPresetsPrivate * priv;
};

struct _MetronomeWidgetsPresetsClass {
	GtkBoxClass parent_class;
};

struct _MetronomeWidgetsPresetsPrivate {
	GtkListBox* list_box;
};

struct _Block1Data {
	int _ref_count_;
	MetronomeWidgetsPresets* self;
	GtkPopover* new_preset_popover;
	GtkEntry* new_preset_title;
};


static gpointer metronome_widgets_presets_parent_class = NULL;

GType metronome_widgets_presets_get_type (void) G_GNUC_CONST;
#define METRONOME_WIDGETS_PRESETS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), METRONOME_WIDGETS_TYPE_PRESETS, MetronomeWidgetsPresetsPrivate))
enum  {
	METRONOME_WIDGETS_PRESETS_DUMMY_PROPERTY
};
MetronomeWidgetsPresets* metronome_widgets_presets_new (void);
MetronomeWidgetsPresets* metronome_widgets_presets_construct (GType object_type);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda5_ (MetronomeWidgetsPresets* self, GtkListBoxRow* row);
gpointer metronome_objects_preset_ref (gpointer instance);
void metronome_objects_preset_unref (gpointer instance);
GParamSpec* metronome_objects_param_spec_preset (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void metronome_objects_value_set_preset (GValue* value, gpointer v_object);
void metronome_objects_value_take_preset (GValue* value, gpointer v_object);
gpointer metronome_objects_value_get_preset (const GValue* value);
GType metronome_objects_preset_get_type (void) G_GNUC_CONST;
GType metronome_widgets_preset_row_get_type (void) G_GNUC_CONST;
MetronomeObjectsPreset* metronome_widgets_preset_row_get_preset (MetronomeWidgetsPresetRow* self);
static void ___lambda5__gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self);
static gboolean __lambda34_ (Block1Data* _data1_, GdkEventKey* event);
MetronomeObjectsPreset* metronome_objects_preset_new (void);
MetronomeObjectsPreset* metronome_objects_preset_construct (GType object_type);
void metronome_objects_preset_set_title (MetronomeObjectsPreset* self, const gchar* value);
GType metronome_metronome_app_get_type (void) G_GNUC_CONST;
MetronomeMetronomeApp* metronome_metronome_app_get_instance (void);
void metronome_metronome_app_push_current_settings_into_preset (MetronomeMetronomeApp* self, MetronomeObjectsPreset* preset);
void metronome_widgets_presets_add_preset (MetronomeWidgetsPresets* self, MetronomeObjectsPreset* preset);
static gboolean ___lambda34__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
static void __lambda35_ (Block1Data* _data1_);
static void ___lambda35__gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self);
MetronomeWidgetsPresetRow* metronome_widgets_preset_row_new (MetronomeObjectsPreset* preset, GtkListBox* parent);
MetronomeWidgetsPresetRow* metronome_widgets_preset_row_construct (GType object_type, MetronomeObjectsPreset* preset, GtkListBox* parent);
const gchar* metronome_objects_preset_get_title (MetronomeObjectsPreset* self);
void metronome_widgets_presets_set_presets (MetronomeWidgetsPresets* self, gchar** presets, int presets_length1);
MetronomeObjectsPreset* metronome_objects_preset_parse (const gchar* custom_settings);
gchar** metronome_widgets_presets_get_presets (MetronomeWidgetsPresets* self, int* result_length1);
gchar* metronome_objects_preset_get_setting_string (MetronomeObjectsPreset* self);
static gchar** _vala_array_dup1 (gchar** self, int length);
static void g_cclosure_user_marshal_VOID__METRONOME_OBJECTS_PRESET (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void metronome_widgets_presets_finalize (GObject* obj);


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	return _data1_;
#line 134 "Presets.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 143 "Presets.c"
		MetronomeWidgetsPresets* self;
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
		self = _data1_->self;
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
		_g_object_unref0 (_data1_->new_preset_title);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
		_g_object_unref0 (_data1_->new_preset_popover);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
		_g_object_unref0 (self);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
		g_slice_free (Block1Data, _data1_);
#line 155 "Presets.c"
	}
}


static gpointer _metronome_objects_preset_ref0 (gpointer self) {
#line 21 "/home/artem/metronome/src/Widgets/Presets.vala"
	return self ? metronome_objects_preset_ref (self) : NULL;
#line 163 "Presets.c"
}


static void __lambda5_ (MetronomeWidgetsPresets* self, GtkListBoxRow* row) {
	MetronomeObjectsPreset* preset = NULL;
	GtkListBoxRow* _tmp0_ = NULL;
	MetronomeObjectsPreset* _tmp1_ = NULL;
	MetronomeObjectsPreset* _tmp2_ = NULL;
	MetronomeObjectsPreset* _tmp3_ = NULL;
#line 20 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_return_if_fail (row != NULL);
#line 21 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp0_ = row;
#line 21 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp1_ = metronome_widgets_preset_row_get_preset (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRow));
#line 21 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp2_ = _tmp1_;
#line 21 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp3_ = _metronome_objects_preset_ref0 (_tmp2_);
#line 21 "/home/artem/metronome/src/Widgets/Presets.vala"
	preset = _tmp3_;
#line 22 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_signal_emit_by_name (self, "preset-selected", preset);
#line 20 "/home/artem/metronome/src/Widgets/Presets.vala"
	_metronome_objects_preset_unref0 (preset);
#line 189 "Presets.c"
}


static void ___lambda5__gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self) {
#line 20 "/home/artem/metronome/src/Widgets/Presets.vala"
	__lambda5_ ((MetronomeWidgetsPresets*) self, row);
#line 196 "Presets.c"
}


static gboolean __lambda34_ (Block1Data* _data1_, GdkEventKey* event) {
	MetronomeWidgetsPresets* self;
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	GdkEventKey* _tmp1_ = NULL;
	guint _tmp2_ = 0U;
#line 58 "/home/artem/metronome/src/Widgets/Presets.vala"
	self = _data1_->self;
#line 58 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 59 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp1_ = event;
#line 59 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp2_ = _tmp1_->keyval;
#line 59 "/home/artem/metronome/src/Widgets/Presets.vala"
	if (_tmp2_ == ((guint) GDK_KEY_Return)) {
#line 59 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp0_ = TRUE;
#line 218 "Presets.c"
	} else {
		GdkEventKey* _tmp3_ = NULL;
		guint _tmp4_ = 0U;
#line 59 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp3_ = event;
#line 59 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp4_ = _tmp3_->keyval;
#line 59 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp0_ = _tmp4_ == ((guint) GDK_KEY_KP_Enter);
#line 228 "Presets.c"
	}
#line 59 "/home/artem/metronome/src/Widgets/Presets.vala"
	if (_tmp0_) {
#line 232 "Presets.c"
		gchar* preset_title = NULL;
		GtkEntryBuffer* _tmp5_ = NULL;
		GtkEntryBuffer* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		const gchar* _tmp10_ = NULL;
#line 60 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp5_ = gtk_entry_get_buffer (_data1_->new_preset_title);
#line 60 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp6_ = _tmp5_;
#line 60 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp7_ = gtk_entry_buffer_get_text (_tmp6_);
#line 60 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp8_ = _tmp7_;
#line 60 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp9_ = g_strdup (_tmp8_);
#line 60 "/home/artem/metronome/src/Widgets/Presets.vala"
		preset_title = _tmp9_;
#line 61 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp10_ = preset_title;
#line 61 "/home/artem/metronome/src/Widgets/Presets.vala"
		if (g_strcmp0 (_tmp10_, "") != 0) {
#line 256 "Presets.c"
			MetronomeObjectsPreset* new_preset = NULL;
			MetronomeObjectsPreset* _tmp11_ = NULL;
			MetronomeObjectsPreset* _tmp12_ = NULL;
			const gchar* _tmp13_ = NULL;
			MetronomeMetronomeApp* _tmp14_ = NULL;
			MetronomeMetronomeApp* _tmp15_ = NULL;
			MetronomeObjectsPreset* _tmp16_ = NULL;
			MetronomeObjectsPreset* _tmp17_ = NULL;
#line 62 "/home/artem/metronome/src/Widgets/Presets.vala"
			_tmp11_ = metronome_objects_preset_new ();
#line 62 "/home/artem/metronome/src/Widgets/Presets.vala"
			new_preset = _tmp11_;
#line 63 "/home/artem/metronome/src/Widgets/Presets.vala"
			_tmp12_ = new_preset;
#line 63 "/home/artem/metronome/src/Widgets/Presets.vala"
			_tmp13_ = preset_title;
#line 63 "/home/artem/metronome/src/Widgets/Presets.vala"
			metronome_objects_preset_set_title (_tmp12_, _tmp13_);
#line 64 "/home/artem/metronome/src/Widgets/Presets.vala"
			_tmp14_ = metronome_metronome_app_get_instance ();
#line 64 "/home/artem/metronome/src/Widgets/Presets.vala"
			_tmp15_ = _tmp14_;
#line 64 "/home/artem/metronome/src/Widgets/Presets.vala"
			_tmp16_ = new_preset;
#line 64 "/home/artem/metronome/src/Widgets/Presets.vala"
			metronome_metronome_app_push_current_settings_into_preset (_tmp15_, _tmp16_);
#line 66 "/home/artem/metronome/src/Widgets/Presets.vala"
			_tmp17_ = new_preset;
#line 66 "/home/artem/metronome/src/Widgets/Presets.vala"
			metronome_widgets_presets_add_preset (self, _tmp17_);
#line 67 "/home/artem/metronome/src/Widgets/Presets.vala"
			gtk_widget_hide ((GtkWidget*) _data1_->new_preset_popover);
#line 68 "/home/artem/metronome/src/Widgets/Presets.vala"
			result = TRUE;
#line 68 "/home/artem/metronome/src/Widgets/Presets.vala"
			_metronome_objects_preset_unref0 (new_preset);
#line 68 "/home/artem/metronome/src/Widgets/Presets.vala"
			_g_free0 (preset_title);
#line 68 "/home/artem/metronome/src/Widgets/Presets.vala"
			return result;
#line 297 "Presets.c"
		}
#line 59 "/home/artem/metronome/src/Widgets/Presets.vala"
		_g_free0 (preset_title);
#line 301 "Presets.c"
	}
#line 71 "/home/artem/metronome/src/Widgets/Presets.vala"
	result = FALSE;
#line 71 "/home/artem/metronome/src/Widgets/Presets.vala"
	return result;
#line 307 "Presets.c"
}


static gboolean ___lambda34__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	gboolean result;
	result = __lambda34_ (self, event);
#line 58 "/home/artem/metronome/src/Widgets/Presets.vala"
	return result;
#line 316 "Presets.c"
}


static void __lambda35_ (Block1Data* _data1_) {
	MetronomeWidgetsPresets* self;
#line 76 "/home/artem/metronome/src/Widgets/Presets.vala"
	self = _data1_->self;
#line 77 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_entry_set_text (_data1_->new_preset_title, "");
#line 78 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_widget_show_all ((GtkWidget*) _data1_->new_preset_popover);
#line 79 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_widget_grab_focus ((GtkWidget*) _data1_->new_preset_title);
#line 330 "Presets.c"
}


static void ___lambda35__gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self) {
#line 76 "/home/artem/metronome/src/Widgets/Presets.vala"
	__lambda35_ (self);
#line 337 "Presets.c"
}


MetronomeWidgetsPresets* metronome_widgets_presets_construct (GType object_type) {
	MetronomeWidgetsPresets * self = NULL;
	Block1Data* _data1_;
	GtkScrolledWindow* list_scroll = NULL;
	GtkScrolledWindow* _tmp0_ = NULL;
	GtkStyleContext* _tmp1_ = NULL;
	GtkListBox* _tmp2_ = NULL;
	GtkListBox* _tmp3_ = NULL;
	GtkListBox* _tmp4_ = NULL;
	GtkListBox* _tmp5_ = NULL;
	GtkToolbar* toolbar = NULL;
	GtkToolbar* _tmp6_ = NULL;
	GtkStyleContext* _tmp7_ = NULL;
	GtkStyleContext* _tmp8_ = NULL;
	GtkSeparatorToolItem* separator = NULL;
	GtkSeparatorToolItem* _tmp9_ = NULL;
	GtkToolButton* add_button = NULL;
	GtkToolButton* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	GtkGrid* popover_grid = NULL;
	GtkGrid* _tmp12_ = NULL;
	GtkPopover* _tmp13_ = NULL;
	GtkEntry* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	_data1_->_ref_count_ = 1;
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	self = (MetronomeWidgetsPresets*) g_object_new (object_type, NULL);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	_data1_->self = g_object_ref (self);
#line 10 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_VERTICAL);
#line 11 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_set ((GtkWidget*) self, "width-request", 160, NULL);
#line 13 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp0_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 13 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_ref_sink (_tmp0_);
#line 13 "/home/artem/metronome/src/Widgets/Presets.vala"
	list_scroll = _tmp0_;
#line 14 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_widget_set_vexpand ((GtkWidget*) list_scroll, TRUE);
#line 15 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) list_scroll);
#line 15 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_style_context_set_junction_sides (_tmp1_, GTK_JUNCTION_BOTTOM);
#line 18 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp2_ = (GtkListBox*) gtk_list_box_new ();
#line 18 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_ref_sink (_tmp2_);
#line 18 "/home/artem/metronome/src/Widgets/Presets.vala"
	_g_object_unref0 (self->priv->list_box);
#line 18 "/home/artem/metronome/src/Widgets/Presets.vala"
	self->priv->list_box = _tmp2_;
#line 19 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp3_ = self->priv->list_box;
#line 19 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_set ((GtkWidget*) _tmp3_, "expand", TRUE, NULL);
#line 20 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp4_ = self->priv->list_box;
#line 20 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_signal_connect_object (_tmp4_, "row-activated", (GCallback) ___lambda5__gtk_list_box_row_activated, self, 0);
#line 25 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp5_ = self->priv->list_box;
#line 25 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_container_add ((GtkContainer*) list_scroll, (GtkWidget*) _tmp5_);
#line 27 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp6_ = (GtkToolbar*) gtk_toolbar_new ();
#line 27 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_ref_sink (_tmp6_);
#line 27 "/home/artem/metronome/src/Widgets/Presets.vala"
	toolbar = _tmp6_;
#line 28 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_set ((GtkWidget*) toolbar, "expand", FALSE, NULL);
#line 29 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_toolbar_set_style (toolbar, GTK_TOOLBAR_ICONS);
#line 30 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_toolbar_set_icon_size (toolbar, GTK_ICON_SIZE_SMALL_TOOLBAR);
#line 31 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_toolbar_set_show_arrow (toolbar, FALSE);
#line 32 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp7_ = gtk_widget_get_style_context ((GtkWidget*) toolbar);
#line 32 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_style_context_add_class (_tmp7_, GTK_STYLE_CLASS_INLINE_TOOLBAR);
#line 33 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp8_ = gtk_widget_get_style_context ((GtkWidget*) toolbar);
#line 33 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_style_context_set_junction_sides (_tmp8_, GTK_JUNCTION_TOP);
#line 35 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp9_ = (GtkSeparatorToolItem*) gtk_separator_tool_item_new ();
#line 35 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_ref_sink (_tmp9_);
#line 35 "/home/artem/metronome/src/Widgets/Presets.vala"
	separator = _tmp9_;
#line 36 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_separator_tool_item_set_draw (separator, FALSE);
#line 37 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_tool_item_set_expand ((GtkToolItem*) separator, TRUE);
#line 38 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_toolbar_insert (toolbar, (GtkToolItem*) separator, -1);
#line 41 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp10_ = (GtkToolButton*) gtk_tool_button_new (NULL, NULL);
#line 41 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_ref_sink (_tmp10_);
#line 41 "/home/artem/metronome/src/Widgets/Presets.vala"
	add_button = _tmp10_;
#line 42 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_tool_button_set_icon_name (add_button, "list-add-symbolic");
#line 43 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp11_ = _ ("Add Preset");
#line 43 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) add_button, _tmp11_);
#line 44 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_toolbar_insert (toolbar, (GtkToolItem*) add_button, -1);
#line 47 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp12_ = (GtkGrid*) gtk_grid_new ();
#line 47 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_ref_sink (_tmp12_);
#line 47 "/home/artem/metronome/src/Widgets/Presets.vala"
	popover_grid = _tmp12_;
#line 48 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_set ((GtkWidget*) popover_grid, "margin", 6, NULL);
#line 50 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp13_ = (GtkPopover*) gtk_popover_new ((GtkWidget*) add_button);
#line 50 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_ref_sink (_tmp13_);
#line 50 "/home/artem/metronome/src/Widgets/Presets.vala"
	_data1_->new_preset_popover = _tmp13_;
#line 51 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_popover_set_position (_data1_->new_preset_popover, GTK_POS_TOP);
#line 52 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_container_add ((GtkContainer*) _data1_->new_preset_popover, (GtkWidget*) popover_grid);
#line 54 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp14_ = (GtkEntry*) gtk_entry_new ();
#line 54 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_ref_sink (_tmp14_);
#line 54 "/home/artem/metronome/src/Widgets/Presets.vala"
	_data1_->new_preset_title = _tmp14_;
#line 55 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_widget_set_hexpand ((GtkWidget*) _data1_->new_preset_title, TRUE);
#line 56 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp15_ = _ ("Preset title");
#line 56 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) _data1_->new_preset_title, _tmp15_);
#line 57 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_entry_set_icon_from_icon_name (_data1_->new_preset_title, GTK_ENTRY_ICON_PRIMARY, "edit-symbolic");
#line 58 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_signal_connect_data ((GtkWidget*) _data1_->new_preset_title, "key-press-event", (GCallback) ___lambda34__gtk_widget_key_press_event, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 74 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_grid_attach (popover_grid, (GtkWidget*) _data1_->new_preset_title, 1, 0, 1, 1);
#line 76 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_signal_connect_data (add_button, "clicked", (GCallback) ___lambda35__gtk_tool_button_clicked, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 82 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) list_scroll, TRUE, TRUE, (guint) 0);
#line 83 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) toolbar, FALSE, FALSE, (guint) 0);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	_g_object_unref0 (popover_grid);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	_g_object_unref0 (add_button);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	_g_object_unref0 (separator);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	_g_object_unref0 (toolbar);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	_g_object_unref0 (list_scroll);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	block1_data_unref (_data1_);
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	_data1_ = NULL;
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	return self;
#line 515 "Presets.c"
}


MetronomeWidgetsPresets* metronome_widgets_presets_new (void) {
#line 9 "/home/artem/metronome/src/Widgets/Presets.vala"
	return metronome_widgets_presets_construct (METRONOME_WIDGETS_TYPE_PRESETS);
#line 522 "Presets.c"
}


void metronome_widgets_presets_add_preset (MetronomeWidgetsPresets* self, MetronomeObjectsPreset* preset) {
	MetronomeWidgetsPresetRow* row = NULL;
	MetronomeObjectsPreset* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	MetronomeWidgetsPresetRow* _tmp2_ = NULL;
	GtkListBox* _tmp3_ = NULL;
	GtkStyleContext* _tmp4_ = NULL;
	MetronomeObjectsPreset* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
#line 87 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_return_if_fail (self != NULL);
#line 87 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_return_if_fail (preset != NULL);
#line 88 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp0_ = preset;
#line 88 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp1_ = self->priv->list_box;
#line 88 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp2_ = metronome_widgets_preset_row_new (_tmp0_, _tmp1_);
#line 88 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_object_ref_sink (_tmp2_);
#line 88 "/home/artem/metronome/src/Widgets/Presets.vala"
	row = _tmp2_;
#line 89 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp3_ = self->priv->list_box;
#line 89 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_container_add ((GtkContainer*) _tmp3_, (GtkWidget*) row);
#line 90 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_widget_show_all ((GtkWidget*) row);
#line 91 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp4_ = gtk_widget_get_style_context ((GtkWidget*) row);
#line 91 "/home/artem/metronome/src/Widgets/Presets.vala"
	gtk_style_context_remove_class (_tmp4_, "button");
#line 92 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp5_ = preset;
#line 92 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp6_ = metronome_objects_preset_get_title (_tmp5_);
#line 92 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp7_ = _tmp6_;
#line 92 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_debug ("Presets.vala:92: add custom setting %s", _tmp7_);
#line 87 "/home/artem/metronome/src/Widgets/Presets.vala"
	_g_object_unref0 (row);
#line 570 "Presets.c"
}


void metronome_widgets_presets_set_presets (MetronomeWidgetsPresets* self, gchar** presets, int presets_length1) {
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
#line 96 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_return_if_fail (self != NULL);
#line 97 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp0_ = presets;
#line 97 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp0__length1 = presets_length1;
#line 583 "Presets.c"
	{
		gchar** item_collection = NULL;
		gint item_collection_length1 = 0;
		gint _item_collection_size_ = 0;
		gint item_it = 0;
#line 97 "/home/artem/metronome/src/Widgets/Presets.vala"
		item_collection = _tmp0_;
#line 97 "/home/artem/metronome/src/Widgets/Presets.vala"
		item_collection_length1 = _tmp0__length1;
#line 97 "/home/artem/metronome/src/Widgets/Presets.vala"
		for (item_it = 0; item_it < _tmp0__length1; item_it = item_it + 1) {
#line 595 "Presets.c"
			gchar* _tmp1_ = NULL;
			gchar* item = NULL;
#line 97 "/home/artem/metronome/src/Widgets/Presets.vala"
			_tmp1_ = g_strdup (item_collection[item_it]);
#line 97 "/home/artem/metronome/src/Widgets/Presets.vala"
			item = _tmp1_;
#line 602 "Presets.c"
			{
				MetronomeObjectsPreset* preset = NULL;
				const gchar* _tmp2_ = NULL;
				MetronomeObjectsPreset* _tmp3_ = NULL;
				MetronomeObjectsPreset* _tmp4_ = NULL;
#line 98 "/home/artem/metronome/src/Widgets/Presets.vala"
				_tmp2_ = item;
#line 98 "/home/artem/metronome/src/Widgets/Presets.vala"
				_tmp3_ = metronome_objects_preset_parse (_tmp2_);
#line 98 "/home/artem/metronome/src/Widgets/Presets.vala"
				preset = _tmp3_;
#line 99 "/home/artem/metronome/src/Widgets/Presets.vala"
				_tmp4_ = preset;
#line 99 "/home/artem/metronome/src/Widgets/Presets.vala"
				if (_tmp4_ != NULL) {
#line 618 "Presets.c"
					MetronomeObjectsPreset* _tmp5_ = NULL;
#line 100 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp5_ = preset;
#line 100 "/home/artem/metronome/src/Widgets/Presets.vala"
					metronome_widgets_presets_add_preset (self, _tmp5_);
#line 624 "Presets.c"
				}
#line 97 "/home/artem/metronome/src/Widgets/Presets.vala"
				_metronome_objects_preset_unref0 (preset);
#line 97 "/home/artem/metronome/src/Widgets/Presets.vala"
				_g_free0 (item);
#line 630 "Presets.c"
			}
		}
	}
}


static gpointer _g_object_ref0 (gpointer self) {
#line 107 "/home/artem/metronome/src/Widgets/Presets.vala"
	return self ? g_object_ref (self) : NULL;
#line 640 "Presets.c"
}


static gchar** _vala_array_dup1 (gchar** self, int length) {
	gchar** result;
	int i;
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	result = g_new0 (gchar*, length + 1);
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	for (i = 0; i < length; i++) {
#line 651 "Presets.c"
		gchar* _tmp0_ = NULL;
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
		_tmp0_ = g_strdup (self[i]);
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
		result[i] = _tmp0_;
#line 657 "Presets.c"
	}
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	return result;
#line 661 "Presets.c"
}


gchar** metronome_widgets_presets_get_presets (MetronomeWidgetsPresets* self, int* result_length1) {
	gchar** result = NULL;
	GArray* custom_settings = NULL;
	GArray* _tmp0_ = NULL;
	GtkListBox* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
	GArray* _tmp15_ = NULL;
	gpointer* _tmp16_ = NULL;
	gint _tmp16__length1 = 0;
	gchar** _tmp17_ = NULL;
	gint _tmp17__length1 = 0;
	gchar** _tmp18_ = NULL;
	gint _tmp18__length1 = 0;
#line 105 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 106 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp0_ = g_array_new (TRUE, TRUE, sizeof (gchar*));
#line 106 "/home/artem/metronome/src/Widgets/Presets.vala"
	custom_settings = _tmp0_;
#line 107 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp1_ = self->priv->list_box;
#line 107 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp2_ = gtk_container_get_children ((GtkContainer*) _tmp1_);
#line 688 "Presets.c"
	{
		GList* row_collection = NULL;
		GList* row_it = NULL;
#line 107 "/home/artem/metronome/src/Widgets/Presets.vala"
		row_collection = _tmp2_;
#line 107 "/home/artem/metronome/src/Widgets/Presets.vala"
		for (row_it = row_collection; row_it != NULL; row_it = row_it->next) {
#line 696 "Presets.c"
			GtkWidget* _tmp3_ = NULL;
			GtkWidget* row = NULL;
#line 107 "/home/artem/metronome/src/Widgets/Presets.vala"
			_tmp3_ = _g_object_ref0 ((GtkWidget*) row_it->data);
#line 107 "/home/artem/metronome/src/Widgets/Presets.vala"
			row = _tmp3_;
#line 703 "Presets.c"
			{
				GtkWidget* _tmp4_ = NULL;
#line 108 "/home/artem/metronome/src/Widgets/Presets.vala"
				_tmp4_ = row;
#line 108 "/home/artem/metronome/src/Widgets/Presets.vala"
				if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp4_, METRONOME_WIDGETS_TYPE_PRESET_ROW)) {
#line 710 "Presets.c"
					GtkWidget* _tmp5_ = NULL;
					MetronomeObjectsPreset* _tmp6_ = NULL;
					MetronomeObjectsPreset* _tmp7_ = NULL;
					gchar* _tmp8_ = NULL;
					gchar* _tmp9_ = NULL;
					GArray* _tmp10_ = NULL;
					GtkWidget* _tmp11_ = NULL;
					MetronomeObjectsPreset* _tmp12_ = NULL;
					MetronomeObjectsPreset* _tmp13_ = NULL;
					gchar* _tmp14_ = NULL;
#line 109 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp5_ = row;
#line 109 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp6_ = metronome_widgets_preset_row_get_preset (G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, METRONOME_WIDGETS_TYPE_PRESET_ROW) ? ((MetronomeWidgetsPresetRow*) _tmp5_) : NULL);
#line 109 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp7_ = _tmp6_;
#line 109 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp8_ = metronome_objects_preset_get_setting_string (_tmp7_);
#line 109 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp9_ = _tmp8_;
#line 109 "/home/artem/metronome/src/Widgets/Presets.vala"
					g_debug ("Presets.vala:109: save custom setting %s", _tmp9_);
#line 109 "/home/artem/metronome/src/Widgets/Presets.vala"
					_g_free0 (_tmp9_);
#line 110 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp10_ = custom_settings;
#line 110 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp11_ = row;
#line 110 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp12_ = metronome_widgets_preset_row_get_preset (G_TYPE_CHECK_INSTANCE_TYPE (_tmp11_, METRONOME_WIDGETS_TYPE_PRESET_ROW) ? ((MetronomeWidgetsPresetRow*) _tmp11_) : NULL);
#line 110 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp13_ = _tmp12_;
#line 110 "/home/artem/metronome/src/Widgets/Presets.vala"
					_tmp14_ = metronome_objects_preset_get_setting_string (_tmp13_);
#line 110 "/home/artem/metronome/src/Widgets/Presets.vala"
					g_array_append_val (_tmp10_, _tmp14_);
#line 747 "Presets.c"
				}
#line 107 "/home/artem/metronome/src/Widgets/Presets.vala"
				_g_object_unref0 (row);
#line 751 "Presets.c"
			}
		}
#line 107 "/home/artem/metronome/src/Widgets/Presets.vala"
		_g_list_free0 (row_collection);
#line 756 "Presets.c"
	}
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp15_ = custom_settings;
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp16_ = _tmp15_->data;
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp16__length1 = (gint) _tmp15_->len;
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp17_ = (_tmp16_ != NULL) ? _vala_array_dup1 (_tmp16_, _tmp16__length1) : ((gpointer) _tmp16_);
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp17__length1 = _tmp16__length1;
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp18_ = _tmp17_;
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	_tmp18__length1 = _tmp17__length1;
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	if (result_length1) {
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
		*result_length1 = _tmp18__length1;
#line 776 "Presets.c"
	}
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	result = _tmp18_;
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	_g_array_unref0 (custom_settings);
#line 113 "/home/artem/metronome/src/Widgets/Presets.vala"
	return result;
#line 784 "Presets.c"
}


static void g_cclosure_user_marshal_VOID__METRONOME_OBJECTS_PRESET (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__METRONOME_OBJECTS_PRESET) (gpointer data1, gpointer arg_1, gpointer data2);
	register GMarshalFunc_VOID__METRONOME_OBJECTS_PRESET callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_return_if_fail (n_param_values == 2);
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
		data1 = closure->data;
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
		data2 = param_values->data[0].v_pointer;
#line 803 "Presets.c"
	} else {
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
		data1 = param_values->data[0].v_pointer;
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
		data2 = closure->data;
#line 809 "Presets.c"
	}
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	callback = (GMarshalFunc_VOID__METRONOME_OBJECTS_PRESET) (marshal_data ? marshal_data : cc->callback);
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	callback (data1, metronome_objects_value_get_preset (param_values + 1), data2);
#line 815 "Presets.c"
}


static void metronome_widgets_presets_class_init (MetronomeWidgetsPresetsClass * klass) {
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	metronome_widgets_presets_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_type_class_add_private (klass, sizeof (MetronomeWidgetsPresetsPrivate));
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	G_OBJECT_CLASS (klass)->finalize = metronome_widgets_presets_finalize;
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	g_signal_new ("preset_selected", METRONOME_WIDGETS_TYPE_PRESETS, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__METRONOME_OBJECTS_PRESET, G_TYPE_NONE, 1, METRONOME_OBJECTS_TYPE_PRESET);
#line 828 "Presets.c"
}


static void metronome_widgets_presets_instance_init (MetronomeWidgetsPresets * self) {
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	self->priv = METRONOME_WIDGETS_PRESETS_GET_PRIVATE (self);
#line 835 "Presets.c"
}


static void metronome_widgets_presets_finalize (GObject* obj) {
	MetronomeWidgetsPresets * self;
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, METRONOME_WIDGETS_TYPE_PRESETS, MetronomeWidgetsPresets);
#line 7 "/home/artem/metronome/src/Widgets/Presets.vala"
	_g_object_unref0 (self->priv->list_box);
#line 3 "/home/artem/metronome/src/Widgets/Presets.vala"
	G_OBJECT_CLASS (metronome_widgets_presets_parent_class)->finalize (obj);
#line 847 "Presets.c"
}


GType metronome_widgets_presets_get_type (void) {
	static volatile gsize metronome_widgets_presets_type_id__volatile = 0;
	if (g_once_init_enter (&metronome_widgets_presets_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MetronomeWidgetsPresetsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) metronome_widgets_presets_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MetronomeWidgetsPresets), 0, (GInstanceInitFunc) metronome_widgets_presets_instance_init, NULL };
		GType metronome_widgets_presets_type_id;
		metronome_widgets_presets_type_id = g_type_register_static (gtk_box_get_type (), "MetronomeWidgetsPresets", &g_define_type_info, 0);
		g_once_init_leave (&metronome_widgets_presets_type_id__volatile, metronome_widgets_presets_type_id);
	}
	return metronome_widgets_presets_type_id__volatile;
}



