/* PresetRow.c generated by valac 0.34.9, the Vala compiler
 * generated from PresetRow.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <granite.h>
#include <gdk/gdk.h>
#include <glib/gi18n-lib.h>


#define METRONOME_WIDGETS_TYPE_PRESET_ROW (metronome_widgets_preset_row_get_type ())
#define METRONOME_WIDGETS_PRESET_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRow))
#define METRONOME_WIDGETS_PRESET_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRowClass))
#define METRONOME_WIDGETS_IS_PRESET_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_WIDGETS_TYPE_PRESET_ROW))
#define METRONOME_WIDGETS_IS_PRESET_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_WIDGETS_TYPE_PRESET_ROW))
#define METRONOME_WIDGETS_PRESET_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRowClass))

typedef struct _MetronomeWidgetsPresetRow MetronomeWidgetsPresetRow;
typedef struct _MetronomeWidgetsPresetRowClass MetronomeWidgetsPresetRowClass;
typedef struct _MetronomeWidgetsPresetRowPrivate MetronomeWidgetsPresetRowPrivate;

#define METRONOME_OBJECTS_TYPE_PRESET (metronome_objects_preset_get_type ())
#define METRONOME_OBJECTS_PRESET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_OBJECTS_TYPE_PRESET, MetronomeObjectsPreset))
#define METRONOME_OBJECTS_PRESET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_OBJECTS_TYPE_PRESET, MetronomeObjectsPresetClass))
#define METRONOME_OBJECTS_IS_PRESET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_OBJECTS_TYPE_PRESET))
#define METRONOME_OBJECTS_IS_PRESET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_OBJECTS_TYPE_PRESET))
#define METRONOME_OBJECTS_PRESET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_OBJECTS_TYPE_PRESET, MetronomeObjectsPresetClass))

typedef struct _MetronomeObjectsPreset MetronomeObjectsPreset;
typedef struct _MetronomeObjectsPresetClass MetronomeObjectsPresetClass;
#define _metronome_objects_preset_unref0(var) ((var == NULL) ? NULL : (var = (metronome_objects_preset_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define METRONOME_WIDGETS_TYPE_ACTION_MENU (metronome_widgets_action_menu_get_type ())
#define METRONOME_WIDGETS_ACTION_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_WIDGETS_TYPE_ACTION_MENU, MetronomeWidgetsActionMenu))
#define METRONOME_WIDGETS_ACTION_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_WIDGETS_TYPE_ACTION_MENU, MetronomeWidgetsActionMenuClass))
#define METRONOME_WIDGETS_IS_ACTION_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_WIDGETS_TYPE_ACTION_MENU))
#define METRONOME_WIDGETS_IS_ACTION_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_WIDGETS_TYPE_ACTION_MENU))
#define METRONOME_WIDGETS_ACTION_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_WIDGETS_TYPE_ACTION_MENU, MetronomeWidgetsActionMenuClass))

typedef struct _MetronomeWidgetsActionMenu MetronomeWidgetsActionMenu;
typedef struct _MetronomeWidgetsActionMenuClass MetronomeWidgetsActionMenuClass;
typedef struct _Block2Data Block2Data;
#define _g_free0(var) (var = (g_free (var), NULL))

#define METRONOME_TYPE_METRONOME_APP (metronome_metronome_app_get_type ())
#define METRONOME_METRONOME_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_TYPE_METRONOME_APP, MetronomeMetronomeApp))
#define METRONOME_METRONOME_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_TYPE_METRONOME_APP, MetronomeMetronomeAppClass))
#define METRONOME_IS_METRONOME_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_TYPE_METRONOME_APP))
#define METRONOME_IS_METRONOME_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_TYPE_METRONOME_APP))
#define METRONOME_METRONOME_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_TYPE_METRONOME_APP, MetronomeMetronomeAppClass))

typedef struct _MetronomeMetronomeApp MetronomeMetronomeApp;
typedef struct _MetronomeMetronomeAppClass MetronomeMetronomeAppClass;
typedef struct _MetronomeWidgetsActionMenuPrivate MetronomeWidgetsActionMenuPrivate;

struct _MetronomeWidgetsPresetRow {
	GtkListBoxRow parent_instance;
	MetronomeWidgetsPresetRowPrivate * priv;
};

struct _MetronomeWidgetsPresetRowClass {
	GtkListBoxRowClass parent_class;
};

struct _MetronomeWidgetsPresetRowPrivate {
	MetronomeObjectsPreset* _preset;
	GtkLabel* title_label;
	GtkLabel* tempo_label;
	GtkLabel* beat_label;
};

struct _Block2Data {
	int _ref_count_;
	MetronomeWidgetsPresetRow* self;
	MetronomeWidgetsActionMenu* menu;
	MetronomeObjectsPreset* preset;
	GtkListBox* parent;
};

struct _MetronomeWidgetsActionMenu {
	GtkRevealer parent_instance;
	MetronomeWidgetsActionMenuPrivate * priv;
};

struct _MetronomeWidgetsActionMenuClass {
	GtkRevealerClass parent_class;
};


static gpointer metronome_widgets_preset_row_parent_class = NULL;
static gpointer metronome_widgets_action_menu_parent_class = NULL;

GType metronome_widgets_preset_row_get_type (void) G_GNUC_CONST;
gpointer metronome_objects_preset_ref (gpointer instance);
void metronome_objects_preset_unref (gpointer instance);
GParamSpec* metronome_objects_param_spec_preset (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void metronome_objects_value_set_preset (GValue* value, gpointer v_object);
void metronome_objects_value_take_preset (GValue* value, gpointer v_object);
gpointer metronome_objects_value_get_preset (const GValue* value);
GType metronome_objects_preset_get_type (void) G_GNUC_CONST;
#define METRONOME_WIDGETS_PRESET_ROW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRowPrivate))
enum  {
	METRONOME_WIDGETS_PRESET_ROW_DUMMY_PROPERTY,
	METRONOME_WIDGETS_PRESET_ROW_PRESET
};
MetronomeWidgetsPresetRow* metronome_widgets_preset_row_new (MetronomeObjectsPreset* preset, GtkListBox* parent);
MetronomeWidgetsPresetRow* metronome_widgets_preset_row_construct (GType object_type, MetronomeObjectsPreset* preset, GtkListBox* parent);
GType metronome_widgets_action_menu_get_type (void) G_GNUC_CONST;
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
void metronome_widgets_preset_row_set_preset (MetronomeWidgetsPresetRow* self, MetronomeObjectsPreset* value);
MetronomeObjectsPreset* metronome_widgets_preset_row_get_preset (MetronomeWidgetsPresetRow* self);
static void __lambda6_ (MetronomeWidgetsPresetRow* self, guint new_beat);
static void ___lambda6__metronome_objects_preset_beat_changed (MetronomeObjectsPreset* _sender, guint beat, gpointer self);
static void __lambda7_ (MetronomeWidgetsPresetRow* self, guint new_tempo);
static void ___lambda7__metronome_objects_preset_tempo_changed (MetronomeObjectsPreset* _sender, guint tempo, gpointer self);
const gchar* metronome_objects_preset_get_title (MetronomeObjectsPreset* self);
guint metronome_objects_preset_get_tempo (MetronomeObjectsPreset* self);
guint metronome_objects_preset_get_beat (MetronomeObjectsPreset* self);
MetronomeWidgetsActionMenu* metronome_widgets_action_menu_new (void);
MetronomeWidgetsActionMenu* metronome_widgets_action_menu_construct (GType object_type);
static void __lambda10_ (Block2Data* _data2_);
static void ___lambda10__metronome_widgets_action_menu_delete_clicked (MetronomeWidgetsActionMenu* _sender, gpointer self);
static void __lambda11_ (Block2Data* _data2_);
GType metronome_metronome_app_get_type (void) G_GNUC_CONST;
MetronomeMetronomeApp* metronome_metronome_app_get_instance (void);
void metronome_metronome_app_push_current_settings_into_preset (MetronomeMetronomeApp* self, MetronomeObjectsPreset* preset);
static void ___lambda11__metronome_widgets_action_menu_save_clicked (MetronomeWidgetsActionMenu* _sender, gpointer self);
static gboolean __lambda32_ (Block2Data* _data2_, GdkEventCrossing* event);
static gboolean ___lambda32__gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self);
static gboolean __lambda33_ (Block2Data* _data2_, GdkEventCrossing* event);
static gboolean ___lambda33__gtk_widget_leave_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self);
static void metronome_widgets_preset_row_finalize (GObject* obj);
static void _vala_metronome_widgets_preset_row_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_metronome_widgets_preset_row_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
enum  {
	METRONOME_WIDGETS_ACTION_MENU_DUMMY_PROPERTY
};
static void __lambda8_ (MetronomeWidgetsActionMenu* self);
static void ___lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda9_ (MetronomeWidgetsActionMenu* self);
static void ___lambda9__gtk_button_clicked (GtkButton* _sender, gpointer self);


static gpointer _metronome_objects_preset_ref0 (gpointer self) {
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return self ? metronome_objects_preset_ref (self) : NULL;
#line 154 "PresetRow.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return self ? g_object_ref (self) : NULL;
#line 161 "PresetRow.c"
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return _data2_;
#line 170 "PresetRow.c"
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 179 "PresetRow.c"
		MetronomeWidgetsPresetRow* self;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		self = _data2_->self;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		_g_object_unref0 (_data2_->menu);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		_metronome_objects_preset_unref0 (_data2_->preset);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		_g_object_unref0 (_data2_->parent);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		_g_object_unref0 (self);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		g_slice_free (Block2Data, _data2_);
#line 193 "PresetRow.c"
	}
}


static void __lambda6_ (MetronomeWidgetsPresetRow* self, guint new_beat) {
	GtkLabel* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 13 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp0_ = self->priv->beat_label;
#line 13 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp1_ = new_beat;
#line 13 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp2_ = g_strdup_printf ("<b>%d</b> Beat", (gint) _tmp1_);
#line 13 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp3_ = _tmp2_;
#line 13 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_label_set_label (_tmp0_, _tmp3_);
#line 13 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_free0 (_tmp3_);
#line 215 "PresetRow.c"
}


static void ___lambda6__metronome_objects_preset_beat_changed (MetronomeObjectsPreset* _sender, guint beat, gpointer self) {
#line 12 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	__lambda6_ ((MetronomeWidgetsPresetRow*) self, beat);
#line 222 "PresetRow.c"
}


static void __lambda7_ (MetronomeWidgetsPresetRow* self, guint new_tempo) {
	GtkLabel* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 16 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp0_ = self->priv->tempo_label;
#line 16 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp1_ = new_tempo;
#line 16 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp2_ = g_strdup_printf ("<b>%d</b> BPM", (gint) _tmp1_);
#line 16 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp3_ = _tmp2_;
#line 16 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_label_set_label (_tmp0_, _tmp3_);
#line 16 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_free0 (_tmp3_);
#line 243 "PresetRow.c"
}


static void ___lambda7__metronome_objects_preset_tempo_changed (MetronomeObjectsPreset* _sender, guint tempo, gpointer self) {
#line 15 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	__lambda7_ ((MetronomeWidgetsPresetRow*) self, tempo);
#line 250 "PresetRow.c"
}


static void __lambda10_ (Block2Data* _data2_) {
	MetronomeWidgetsPresetRow* self;
	GtkListBox* _tmp0_ = NULL;
#line 46 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self = _data2_->self;
#line 47 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp0_ = _data2_->parent;
#line 47 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_container_remove ((GtkContainer*) _tmp0_, (GtkWidget*) self);
#line 263 "PresetRow.c"
}


static void ___lambda10__metronome_widgets_action_menu_delete_clicked (MetronomeWidgetsActionMenu* _sender, gpointer self) {
#line 46 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	__lambda10_ (self);
#line 270 "PresetRow.c"
}


static void __lambda11_ (Block2Data* _data2_) {
	MetronomeWidgetsPresetRow* self;
	MetronomeMetronomeApp* _tmp0_ = NULL;
	MetronomeMetronomeApp* _tmp1_ = NULL;
	MetronomeObjectsPreset* _tmp2_ = NULL;
#line 49 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self = _data2_->self;
#line 50 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp0_ = metronome_metronome_app_get_instance ();
#line 50 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp1_ = _tmp0_;
#line 50 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp2_ = _data2_->preset;
#line 50 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	metronome_metronome_app_push_current_settings_into_preset (_tmp1_, _tmp2_);
#line 289 "PresetRow.c"
}


static void ___lambda11__metronome_widgets_action_menu_save_clicked (MetronomeWidgetsActionMenu* _sender, gpointer self) {
#line 49 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	__lambda11_ (self);
#line 296 "PresetRow.c"
}


static gboolean __lambda32_ (Block2Data* _data2_, GdkEventCrossing* event) {
	MetronomeWidgetsPresetRow* self;
	gboolean result = FALSE;
#line 62 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self = _data2_->self;
#line 62 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 63 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_revealer_set_reveal_child ((GtkRevealer*) _data2_->menu, TRUE);
#line 64 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	result = FALSE;
#line 64 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return result;
#line 313 "PresetRow.c"
}


static gboolean ___lambda32__gtk_widget_enter_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self) {
	gboolean result;
	result = __lambda32_ (self, event);
#line 62 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return result;
#line 322 "PresetRow.c"
}


static gboolean __lambda33_ (Block2Data* _data2_, GdkEventCrossing* event) {
	MetronomeWidgetsPresetRow* self;
	gboolean result = FALSE;
	GdkEventCrossing* _tmp0_ = NULL;
	GdkNotifyType _tmp1_ = 0;
#line 67 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self = _data2_->self;
#line 67 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 68 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp0_ = event;
#line 68 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp1_ = _tmp0_->detail;
#line 68 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	if (_tmp1_ == GDK_NOTIFY_INFERIOR) {
#line 69 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		result = FALSE;
#line 69 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		return result;
#line 345 "PresetRow.c"
	}
#line 70 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_revealer_set_reveal_child ((GtkRevealer*) _data2_->menu, FALSE);
#line 71 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	result = FALSE;
#line 71 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return result;
#line 353 "PresetRow.c"
}


static gboolean ___lambda33__gtk_widget_leave_notify_event (GtkWidget* _sender, GdkEventCrossing* event, gpointer self) {
	gboolean result;
	result = __lambda33_ (self, event);
#line 67 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return result;
#line 362 "PresetRow.c"
}


MetronomeWidgetsPresetRow* metronome_widgets_preset_row_construct (GType object_type, MetronomeObjectsPreset* preset, GtkListBox* parent) {
	MetronomeWidgetsPresetRow * self = NULL;
	Block2Data* _data2_;
	MetronomeObjectsPreset* _tmp0_ = NULL;
	MetronomeObjectsPreset* _tmp1_ = NULL;
	GtkListBox* _tmp2_ = NULL;
	GtkListBox* _tmp3_ = NULL;
	MetronomeObjectsPreset* _tmp4_ = NULL;
	MetronomeObjectsPreset* _tmp5_ = NULL;
	MetronomeObjectsPreset* _tmp6_ = NULL;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp7_ = NULL;
	MetronomeObjectsPreset* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	GtkLabel* _tmp11_ = NULL;
	GtkLabel* _tmp12_ = NULL;
	GtkLabel* _tmp13_ = NULL;
	GtkStyleContext* _tmp14_ = NULL;
	GtkLabel* _tmp15_ = NULL;
	MetronomeObjectsPreset* _tmp16_ = NULL;
	guint _tmp17_ = 0U;
	guint _tmp18_ = 0U;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	GtkLabel* _tmp21_ = NULL;
	GtkLabel* _tmp22_ = NULL;
	GtkLabel* _tmp23_ = NULL;
	GtkLabel* _tmp24_ = NULL;
	GtkLabel* _tmp25_ = NULL;
	MetronomeObjectsPreset* _tmp26_ = NULL;
	guint _tmp27_ = 0U;
	guint _tmp28_ = 0U;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	GtkLabel* _tmp31_ = NULL;
	GtkLabel* _tmp32_ = NULL;
	GtkLabel* _tmp33_ = NULL;
	GtkLabel* _tmp34_ = NULL;
	GtkLabel* _tmp35_ = NULL;
	MetronomeWidgetsActionMenu* _tmp36_ = NULL;
	GtkLabel* _tmp37_ = NULL;
	GtkLabel* _tmp38_ = NULL;
	GtkLabel* _tmp39_ = NULL;
	GtkSeparator* _tmp40_ = NULL;
	GtkSeparator* _tmp41_ = NULL;
	GtkEventBox* event_box = NULL;
	GtkEventBox* _tmp42_ = NULL;
	GdkEventMask _tmp43_ = 0;
	GdkEventMask _tmp44_ = 0;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_return_val_if_fail (preset != NULL, NULL);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_return_val_if_fail (parent != NULL, NULL);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_data2_ = g_slice_new0 (Block2Data);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_data2_->_ref_count_ = 1;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp0_ = preset;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp1_ = _metronome_objects_preset_ref0 (_tmp0_);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_metronome_objects_preset_unref0 (_data2_->preset);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_data2_->preset = _tmp1_;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp2_ = parent;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (_data2_->parent);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_data2_->parent = _tmp3_;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self = (MetronomeWidgetsPresetRow*) g_object_new (object_type, NULL);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_data2_->self = g_object_ref (self);
#line 11 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp4_ = _data2_->preset;
#line 11 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	metronome_widgets_preset_row_set_preset (self, _tmp4_);
#line 12 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp5_ = self->priv->_preset;
#line 12 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_connect_object (_tmp5_, "beat-changed", (GCallback) ___lambda6__metronome_objects_preset_beat_changed, self, 0);
#line 15 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp6_ = self->priv->_preset;
#line 15 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_connect_object (_tmp6_, "tempo-changed", (GCallback) ___lambda7__metronome_objects_preset_tempo_changed, self, 0);
#line 19 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp7_ = (GtkGrid*) gtk_grid_new ();
#line 19 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp7_);
#line 19 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	grid = _tmp7_;
#line 20 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_margin_top ((GtkWidget*) grid, 4);
#line 21 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_grid_set_row_spacing (grid, 4);
#line 22 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_set ((GtkWidget*) grid, "expand", TRUE, NULL);
#line 25 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp8_ = _data2_->preset;
#line 25 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp9_ = metronome_objects_preset_get_title (_tmp8_);
#line 25 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp10_ = _tmp9_;
#line 25 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp11_ = (GtkLabel*) gtk_label_new (_tmp10_);
#line 25 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp11_);
#line 25 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (self->priv->title_label);
#line 25 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self->priv->title_label = _tmp11_;
#line 26 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp12_ = self->priv->title_label;
#line 26 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp12_, GTK_ALIGN_START);
#line 27 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp13_ = self->priv->title_label;
#line 27 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp14_ = gtk_widget_get_style_context ((GtkWidget*) _tmp13_);
#line 27 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_style_context_add_class (_tmp14_, "h3");
#line 28 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp15_ = self->priv->title_label;
#line 28 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_set ((GtkWidget*) _tmp15_, "expand", TRUE, NULL);
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp16_ = _data2_->preset;
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp17_ = metronome_objects_preset_get_tempo (_tmp16_);
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp18_ = _tmp17_;
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp19_ = g_strdup_printf ("<b>%d</b> BPM", (gint) _tmp18_);
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp20_ = _tmp19_;
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp21_ = (GtkLabel*) gtk_label_new (_tmp20_);
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp21_);
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (self->priv->tempo_label);
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self->priv->tempo_label = _tmp21_;
#line 30 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_free0 (_tmp20_);
#line 31 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp22_ = self->priv->tempo_label;
#line 31 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_label_set_use_markup (_tmp22_, TRUE);
#line 32 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp23_ = self->priv->tempo_label;
#line 32 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp23_, GTK_ALIGN_END);
#line 33 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp24_ = self->priv->tempo_label;
#line 33 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_opacity ((GtkWidget*) _tmp24_, 0.6);
#line 34 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp25_ = self->priv->tempo_label;
#line 34 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_margin_right ((GtkWidget*) _tmp25_, 12);
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp26_ = _data2_->preset;
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp27_ = metronome_objects_preset_get_beat (_tmp26_);
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp28_ = _tmp27_;
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp29_ = g_strdup_printf ("<b>%d</b> Beat", (gint) _tmp28_);
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp30_ = _tmp29_;
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp31_ = (GtkLabel*) gtk_label_new (_tmp30_);
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp31_);
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (self->priv->beat_label);
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self->priv->beat_label = _tmp31_;
#line 36 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_free0 (_tmp30_);
#line 37 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp32_ = self->priv->beat_label;
#line 37 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_label_set_use_markup (_tmp32_, TRUE);
#line 38 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp33_ = self->priv->beat_label;
#line 38 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp33_, GTK_ALIGN_END);
#line 39 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp34_ = self->priv->beat_label;
#line 39 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_opacity ((GtkWidget*) _tmp34_, 0.6);
#line 40 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp35_ = self->priv->beat_label;
#line 40 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_margin_right ((GtkWidget*) _tmp35_, 6);
#line 44 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp36_ = metronome_widgets_action_menu_new ();
#line 44 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp36_);
#line 44 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_data2_->menu = _tmp36_;
#line 45 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_valign ((GtkWidget*) _data2_->menu, GTK_ALIGN_START);
#line 46 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_connect_data (_data2_->menu, "delete-clicked", (GCallback) ___lambda10__metronome_widgets_action_menu_delete_clicked, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 49 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_connect_data (_data2_->menu, "save-clicked", (GCallback) ___lambda11__metronome_widgets_action_menu_save_clicked, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 52 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_grid_attach (grid, (GtkWidget*) _data2_->menu, 0, 0, 1, 2);
#line 53 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp37_ = self->priv->title_label;
#line 53 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp37_, 1, 0, 1, 1);
#line 54 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp38_ = self->priv->tempo_label;
#line 54 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp38_, 1, 1, 1, 1);
#line 55 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp39_ = self->priv->beat_label;
#line 55 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp39_, 2, 1, 1, 1);
#line 56 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp40_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
#line 56 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp40_);
#line 56 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp41_ = _tmp40_;
#line 56 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp41_, 0, 2, 3, 1);
#line 56 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (_tmp41_);
#line 58 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp42_ = (GtkEventBox*) gtk_event_box_new ();
#line 58 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp42_);
#line 58 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	event_box = _tmp42_;
#line 59 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_container_add ((GtkContainer*) event_box, (GtkWidget*) grid);
#line 60 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp43_ = gtk_widget_get_events ((GtkWidget*) event_box);
#line 60 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp44_ = _tmp43_;
#line 60 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_events ((GtkWidget*) event_box, _tmp44_ | (GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK));
#line 62 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_connect_data ((GtkWidget*) event_box, "enter-notify-event", (GCallback) ___lambda32__gtk_widget_enter_notify_event, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 67 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_connect_data ((GtkWidget*) event_box, "leave-notify-event", (GCallback) ___lambda33__gtk_widget_leave_notify_event, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 74 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) event_box);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (event_box);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (grid);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	block2_data_unref (_data2_);
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_data2_ = NULL;
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return self;
#line 634 "PresetRow.c"
}


MetronomeWidgetsPresetRow* metronome_widgets_preset_row_new (MetronomeObjectsPreset* preset, GtkListBox* parent) {
#line 10 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return metronome_widgets_preset_row_construct (METRONOME_WIDGETS_TYPE_PRESET_ROW, preset, parent);
#line 641 "PresetRow.c"
}


MetronomeObjectsPreset* metronome_widgets_preset_row_get_preset (MetronomeWidgetsPresetRow* self) {
	MetronomeObjectsPreset* result;
	MetronomeObjectsPreset* _tmp0_ = NULL;
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp0_ = self->priv->_preset;
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	result = _tmp0_;
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return result;
#line 656 "PresetRow.c"
}


void metronome_widgets_preset_row_set_preset (MetronomeWidgetsPresetRow* self, MetronomeObjectsPreset* value) {
	MetronomeObjectsPreset* _tmp0_ = NULL;
	MetronomeObjectsPreset* _tmp1_ = NULL;
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_return_if_fail (self != NULL);
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp0_ = value;
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp1_ = _metronome_objects_preset_ref0 (_tmp0_);
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_metronome_objects_preset_unref0 (self->priv->_preset);
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self->priv->_preset = _tmp1_;
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_notify ((GObject *) self, "preset");
#line 675 "PresetRow.c"
}


static void metronome_widgets_preset_row_class_init (MetronomeWidgetsPresetRowClass * klass) {
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	metronome_widgets_preset_row_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_type_class_add_private (klass, sizeof (MetronomeWidgetsPresetRowPrivate));
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_metronome_widgets_preset_row_get_property;
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_metronome_widgets_preset_row_set_property;
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	G_OBJECT_CLASS (klass)->finalize = metronome_widgets_preset_row_finalize;
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), METRONOME_WIDGETS_PRESET_ROW_PRESET, metronome_objects_param_spec_preset ("preset", "preset", "preset", METRONOME_OBJECTS_TYPE_PRESET, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 692 "PresetRow.c"
}


static void metronome_widgets_preset_row_instance_init (MetronomeWidgetsPresetRow * self) {
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self->priv = METRONOME_WIDGETS_PRESET_ROW_GET_PRIVATE (self);
#line 699 "PresetRow.c"
}


static void metronome_widgets_preset_row_finalize (GObject* obj) {
	MetronomeWidgetsPresetRow * self;
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRow);
#line 4 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_metronome_objects_preset_unref0 (self->priv->_preset);
#line 6 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (self->priv->title_label);
#line 7 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (self->priv->tempo_label);
#line 8 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (self->priv->beat_label);
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	G_OBJECT_CLASS (metronome_widgets_preset_row_parent_class)->finalize (obj);
#line 717 "PresetRow.c"
}


GType metronome_widgets_preset_row_get_type (void) {
	static volatile gsize metronome_widgets_preset_row_type_id__volatile = 0;
	if (g_once_init_enter (&metronome_widgets_preset_row_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MetronomeWidgetsPresetRowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) metronome_widgets_preset_row_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MetronomeWidgetsPresetRow), 0, (GInstanceInitFunc) metronome_widgets_preset_row_instance_init, NULL };
		GType metronome_widgets_preset_row_type_id;
		metronome_widgets_preset_row_type_id = g_type_register_static (gtk_list_box_row_get_type (), "MetronomeWidgetsPresetRow", &g_define_type_info, 0);
		g_once_init_leave (&metronome_widgets_preset_row_type_id__volatile, metronome_widgets_preset_row_type_id);
	}
	return metronome_widgets_preset_row_type_id__volatile;
}


static void _vala_metronome_widgets_preset_row_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MetronomeWidgetsPresetRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRow);
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	switch (property_id) {
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		case METRONOME_WIDGETS_PRESET_ROW_PRESET:
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		metronome_objects_value_set_preset (value, metronome_widgets_preset_row_get_preset (self));
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		break;
#line 744 "PresetRow.c"
		default:
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		break;
#line 750 "PresetRow.c"
	}
}


static void _vala_metronome_widgets_preset_row_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MetronomeWidgetsPresetRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, METRONOME_WIDGETS_TYPE_PRESET_ROW, MetronomeWidgetsPresetRow);
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	switch (property_id) {
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		case METRONOME_WIDGETS_PRESET_ROW_PRESET:
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		metronome_widgets_preset_row_set_preset (self, metronome_objects_value_get_preset (value));
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		break;
#line 766 "PresetRow.c"
		default:
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/artem/metronome/src/Widgets/PresetRow.vala"
		break;
#line 772 "PresetRow.c"
	}
}


static void __lambda8_ (MetronomeWidgetsActionMenu* self) {
#line 87 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_emit_by_name (self, "delete-clicked");
#line 780 "PresetRow.c"
}


static void ___lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 87 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	__lambda8_ ((MetronomeWidgetsActionMenu*) self);
#line 787 "PresetRow.c"
}


static void __lambda9_ (MetronomeWidgetsActionMenu* self) {
#line 92 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_emit_by_name (self, "save-clicked");
#line 794 "PresetRow.c"
}


static void ___lambda9__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 92 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	__lambda9_ ((MetronomeWidgetsActionMenu*) self);
#line 801 "PresetRow.c"
}


MetronomeWidgetsActionMenu* metronome_widgets_action_menu_construct (GType object_type) {
	MetronomeWidgetsActionMenu * self = NULL;
	GtkButton* delete_button = NULL;
	GtkButton* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkButton* save_button = NULL;
	GtkButton* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GtkGrid* buttons = NULL;
	GtkGrid* _tmp4_ = NULL;
#line 83 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	self = (MetronomeWidgetsActionMenu*) g_object_new (object_type, NULL);
#line 84 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp0_ = (GtkButton*) gtk_button_new_from_icon_name ("edit-delete-symbolic", GTK_ICON_SIZE_BUTTON);
#line 84 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp0_);
#line 84 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	delete_button = _tmp0_;
#line 85 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp1_ = _ ("Delete Preset");
#line 85 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) delete_button, _tmp1_);
#line 86 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_button_set_relief (delete_button, GTK_RELIEF_NONE);
#line 87 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_connect_object (delete_button, "clicked", (GCallback) ___lambda8__gtk_button_clicked, self, 0);
#line 89 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp2_ = (GtkButton*) gtk_button_new_from_icon_name ("document-save-symbolic", GTK_ICON_SIZE_BUTTON);
#line 89 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp2_);
#line 89 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	save_button = _tmp2_;
#line 90 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp3_ = _ ("Save current Settings");
#line 90 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) save_button, _tmp3_);
#line 91 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_button_set_relief (save_button, GTK_RELIEF_NONE);
#line 92 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_connect_object (save_button, "clicked", (GCallback) ___lambda9__gtk_button_clicked, self, 0);
#line 94 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_tmp4_ = (GtkGrid*) gtk_grid_new ();
#line 94 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_object_ref_sink (_tmp4_);
#line 94 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	buttons = _tmp4_;
#line 95 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_orientable_set_orientation ((GtkOrientable*) buttons, GTK_ORIENTATION_VERTICAL);
#line 96 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_container_add ((GtkContainer*) buttons, (GtkWidget*) save_button);
#line 97 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_container_add ((GtkContainer*) buttons, (GtkWidget*) delete_button);
#line 98 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_widget_set_opacity ((GtkWidget*) buttons, 0.5);
#line 100 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_revealer_set_transition_type ((GtkRevealer*) self, GTK_REVEALER_TRANSITION_TYPE_CROSSFADE);
#line 101 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) buttons);
#line 83 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (buttons);
#line 83 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (save_button);
#line 83 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	_g_object_unref0 (delete_button);
#line 83 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return self;
#line 871 "PresetRow.c"
}


MetronomeWidgetsActionMenu* metronome_widgets_action_menu_new (void) {
#line 83 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	return metronome_widgets_action_menu_construct (METRONOME_WIDGETS_TYPE_ACTION_MENU);
#line 878 "PresetRow.c"
}


static void metronome_widgets_action_menu_class_init (MetronomeWidgetsActionMenuClass * klass) {
#line 78 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	metronome_widgets_action_menu_parent_class = g_type_class_peek_parent (klass);
#line 78 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_new ("delete_clicked", METRONOME_WIDGETS_TYPE_ACTION_MENU, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 78 "/home/artem/metronome/src/Widgets/PresetRow.vala"
	g_signal_new ("save_clicked", METRONOME_WIDGETS_TYPE_ACTION_MENU, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 889 "PresetRow.c"
}


static void metronome_widgets_action_menu_instance_init (MetronomeWidgetsActionMenu * self) {
}


GType metronome_widgets_action_menu_get_type (void) {
	static volatile gsize metronome_widgets_action_menu_type_id__volatile = 0;
	if (g_once_init_enter (&metronome_widgets_action_menu_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MetronomeWidgetsActionMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) metronome_widgets_action_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MetronomeWidgetsActionMenu), 0, (GInstanceInitFunc) metronome_widgets_action_menu_instance_init, NULL };
		GType metronome_widgets_action_menu_type_id;
		metronome_widgets_action_menu_type_id = g_type_register_static (gtk_revealer_get_type (), "MetronomeWidgetsActionMenu", &g_define_type_info, 0);
		g_once_init_leave (&metronome_widgets_action_menu_type_id__volatile, metronome_widgets_action_menu_type_id);
	}
	return metronome_widgets_action_menu_type_id__volatile;
}



