/* Volumes.c generated by valac 0.34.9, the Vala compiler
 * generated from Volumes.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define METRONOME_WIDGETS_TYPE_VOLUMES (metronome_widgets_volumes_get_type ())
#define METRONOME_WIDGETS_VOLUMES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), METRONOME_WIDGETS_TYPE_VOLUMES, MetronomeWidgetsVolumes))
#define METRONOME_WIDGETS_VOLUMES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), METRONOME_WIDGETS_TYPE_VOLUMES, MetronomeWidgetsVolumesClass))
#define METRONOME_WIDGETS_IS_VOLUMES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), METRONOME_WIDGETS_TYPE_VOLUMES))
#define METRONOME_WIDGETS_IS_VOLUMES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), METRONOME_WIDGETS_TYPE_VOLUMES))
#define METRONOME_WIDGETS_VOLUMES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), METRONOME_WIDGETS_TYPE_VOLUMES, MetronomeWidgetsVolumesClass))

typedef struct _MetronomeWidgetsVolumes MetronomeWidgetsVolumes;
typedef struct _MetronomeWidgetsVolumesClass MetronomeWidgetsVolumesClass;
typedef struct _MetronomeWidgetsVolumesPrivate MetronomeWidgetsVolumesPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _MetronomeWidgetsVolumes {
	GtkGrid parent_instance;
	MetronomeWidgetsVolumesPrivate * priv;
};

struct _MetronomeWidgetsVolumesClass {
	GtkGridClass parent_class;
};

struct _MetronomeWidgetsVolumesPrivate {
	GtkScale* scale_semibreve;
	GtkScale* scale_minim;
	GtkScale* scale_crotchet;
	GtkScale* scale_quaver;
	gdouble vol_semibreve;
	gdouble vol_minim;
	gdouble vol_crotchet;
	gdouble vol_quaver;
};


static gpointer metronome_widgets_volumes_parent_class = NULL;

GType metronome_widgets_volumes_get_type (void) G_GNUC_CONST;
#define METRONOME_WIDGETS_VOLUMES_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), METRONOME_WIDGETS_TYPE_VOLUMES, MetronomeWidgetsVolumesPrivate))
enum  {
	METRONOME_WIDGETS_VOLUMES_DUMMY_PROPERTY,
	METRONOME_WIDGETS_VOLUMES_VOLUME_SEMIBREVE,
	METRONOME_WIDGETS_VOLUMES_VOLUME_MINIM,
	METRONOME_WIDGETS_VOLUMES_VOLUME_CROTCHET,
	METRONOME_WIDGETS_VOLUMES_VOLUME_QUAVER
};
MetronomeWidgetsVolumes* metronome_widgets_volumes_new (void);
MetronomeWidgetsVolumes* metronome_widgets_volumes_construct (GType object_type);
static void __lambda12_ (MetronomeWidgetsVolumes* self);
static void ___lambda12__gtk_range_value_changed (GtkRange* _sender, gpointer self);
#define CONSTANTS_PKGDATADIR "/usr/share/metronome"
static void __lambda13_ (MetronomeWidgetsVolumes* self);
static void ___lambda13__gtk_range_value_changed (GtkRange* _sender, gpointer self);
static void __lambda14_ (MetronomeWidgetsVolumes* self);
static void ___lambda14__gtk_range_value_changed (GtkRange* _sender, gpointer self);
static void __lambda15_ (MetronomeWidgetsVolumes* self);
static void ___lambda15__gtk_range_value_changed (GtkRange* _sender, gpointer self);
gdouble metronome_widgets_volumes_get_volume_semibreve (MetronomeWidgetsVolumes* self);
void metronome_widgets_volumes_set_volume_semibreve (MetronomeWidgetsVolumes* self, gdouble value);
gdouble metronome_widgets_volumes_get_volume_minim (MetronomeWidgetsVolumes* self);
void metronome_widgets_volumes_set_volume_minim (MetronomeWidgetsVolumes* self, gdouble value);
gdouble metronome_widgets_volumes_get_volume_crotchet (MetronomeWidgetsVolumes* self);
void metronome_widgets_volumes_set_volume_crotchet (MetronomeWidgetsVolumes* self, gdouble value);
gdouble metronome_widgets_volumes_get_volume_quaver (MetronomeWidgetsVolumes* self);
void metronome_widgets_volumes_set_volume_quaver (MetronomeWidgetsVolumes* self, gdouble value);
static void metronome_widgets_volumes_finalize (GObject* obj);
static void _vala_metronome_widgets_volumes_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_metronome_widgets_volumes_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void __lambda12_ (MetronomeWidgetsVolumes* self) {
	gdouble _result_ = 0.0;
	GtkScale* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
#line 27 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->scale_semibreve;
#line 27 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp1_ = gtk_range_get_value ((GtkRange*) _tmp0_);
#line 27 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_result_ = ((gdouble) ((gint) (_tmp1_ * 100))) / 100;
#line 28 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->vol_semibreve = _result_;
#line 29 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp2_ = self->priv->vol_semibreve;
#line 29 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_debug ("Volumes.vala:29: Volume semibreve %g", _tmp2_);
#line 100 "Volumes.c"
}


static void ___lambda12__gtk_range_value_changed (GtkRange* _sender, gpointer self) {
#line 26 "/home/artem/metronome/src/Widgets/Volumes.vala"
	__lambda12_ ((MetronomeWidgetsVolumes*) self);
#line 107 "Volumes.c"
}


static void __lambda13_ (MetronomeWidgetsVolumes* self) {
	gdouble _result_ = 0.0;
	GtkScale* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
#line 39 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->scale_minim;
#line 39 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp1_ = gtk_range_get_value ((GtkRange*) _tmp0_);
#line 39 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_result_ = ((gdouble) ((gint) (_tmp1_ * 100))) / 100;
#line 40 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->vol_minim = _result_;
#line 41 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp2_ = self->priv->vol_minim;
#line 41 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_debug ("Volumes.vala:41: Volume minim %g", _tmp2_);
#line 128 "Volumes.c"
}


static void ___lambda13__gtk_range_value_changed (GtkRange* _sender, gpointer self) {
#line 38 "/home/artem/metronome/src/Widgets/Volumes.vala"
	__lambda13_ ((MetronomeWidgetsVolumes*) self);
#line 135 "Volumes.c"
}


static void __lambda14_ (MetronomeWidgetsVolumes* self) {
	gdouble _result_ = 0.0;
	GtkScale* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
#line 51 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->scale_crotchet;
#line 51 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp1_ = gtk_range_get_value ((GtkRange*) _tmp0_);
#line 51 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_result_ = ((gdouble) ((gint) (_tmp1_ * 100))) / 100;
#line 52 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->vol_crotchet = _result_;
#line 53 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp2_ = self->priv->vol_crotchet;
#line 53 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_debug ("Volumes.vala:53: Volume crotchet %g", _tmp2_);
#line 156 "Volumes.c"
}


static void ___lambda14__gtk_range_value_changed (GtkRange* _sender, gpointer self) {
#line 50 "/home/artem/metronome/src/Widgets/Volumes.vala"
	__lambda14_ ((MetronomeWidgetsVolumes*) self);
#line 163 "Volumes.c"
}


static void __lambda15_ (MetronomeWidgetsVolumes* self) {
	gdouble _result_ = 0.0;
	GtkScale* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
#line 63 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->scale_quaver;
#line 63 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp1_ = gtk_range_get_value ((GtkRange*) _tmp0_);
#line 63 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_result_ = ((gdouble) ((gint) (_tmp1_ * 100))) / 100;
#line 64 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->vol_quaver = _result_;
#line 65 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp2_ = self->priv->vol_quaver;
#line 65 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_debug ("Volumes.vala:65: Volume quaver %g", _tmp2_);
#line 184 "Volumes.c"
}


static void ___lambda15__gtk_range_value_changed (GtkRange* _sender, gpointer self) {
#line 62 "/home/artem/metronome/src/Widgets/Volumes.vala"
	__lambda15_ ((MetronomeWidgetsVolumes*) self);
#line 191 "Volumes.c"
}


MetronomeWidgetsVolumes* metronome_widgets_volumes_construct (GType object_type) {
	MetronomeWidgetsVolumes * self = NULL;
	GtkScale* _tmp0_ = NULL;
	GtkScale* _tmp1_ = NULL;
	GtkScale* _tmp2_ = NULL;
	GtkScale* _tmp3_ = NULL;
	GtkScale* _tmp4_ = NULL;
	GtkScale* _tmp5_ = NULL;
	GtkImage* icon_semibreve = NULL;
	GtkImage* _tmp6_ = NULL;
	GtkScale* _tmp7_ = NULL;
	GtkScale* _tmp8_ = NULL;
	GtkScale* _tmp9_ = NULL;
	GtkScale* _tmp10_ = NULL;
	GtkScale* _tmp11_ = NULL;
	GtkImage* icon_minim = NULL;
	GtkImage* _tmp12_ = NULL;
	GtkScale* _tmp13_ = NULL;
	GtkScale* _tmp14_ = NULL;
	GtkScale* _tmp15_ = NULL;
	GtkScale* _tmp16_ = NULL;
	GtkScale* _tmp17_ = NULL;
	GtkImage* icon_crotchet = NULL;
	GtkImage* _tmp18_ = NULL;
	GtkScale* _tmp19_ = NULL;
	GtkScale* _tmp20_ = NULL;
	GtkScale* _tmp21_ = NULL;
	GtkScale* _tmp22_ = NULL;
	GtkScale* _tmp23_ = NULL;
	GtkImage* icon_quaver = NULL;
	GtkImage* _tmp24_ = NULL;
	GtkScale* _tmp25_ = NULL;
	GtkScale* _tmp26_ = NULL;
	GtkScale* _tmp27_ = NULL;
	GtkScale* _tmp28_ = NULL;
#line 15 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self = (MetronomeWidgetsVolumes*) g_object_new (object_type, NULL);
#line 16 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_widget_set_hexpand ((GtkWidget*) self, TRUE);
#line 17 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_set_row_spacing ((GtkGrid*) self, 6);
#line 18 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_set_column_spacing ((GtkGrid*) self, 6);
#line 19 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_set ((GtkWidget*) self, "height-request", 180, NULL);
#line 21 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = (GtkScale*) gtk_scale_new_with_range (GTK_ORIENTATION_VERTICAL, (gdouble) 0, (gdouble) 1, 0.01);
#line 21 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_ref_sink (_tmp0_);
#line 21 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (self->priv->scale_semibreve);
#line 21 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->scale_semibreve = _tmp0_;
#line 22 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp1_ = self->priv->scale_semibreve;
#line 22 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_set ((GtkWidget*) _tmp1_, "expand", TRUE, NULL);
#line 23 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp2_ = self->priv->scale_semibreve;
#line 23 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_range_set_inverted ((GtkRange*) _tmp2_, TRUE);
#line 24 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp3_ = self->priv->scale_semibreve;
#line 24 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_scale_set_draw_value (_tmp3_, FALSE);
#line 25 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp4_ = self->priv->scale_semibreve;
#line 25 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_range_set_value ((GtkRange*) _tmp4_, 0.5);
#line 26 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp5_ = self->priv->scale_semibreve;
#line 26 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_signal_connect_object ((GtkRange*) _tmp5_, "value-changed", (GCallback) ___lambda12__gtk_range_value_changed, self, 0);
#line 32 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp6_ = (GtkImage*) gtk_image_new_from_file (CONSTANTS_PKGDATADIR "/icons/symbol_semibreve.png");
#line 32 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_ref_sink (_tmp6_);
#line 32 "/home/artem/metronome/src/Widgets/Volumes.vala"
	icon_semibreve = _tmp6_;
#line 34 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp7_ = (GtkScale*) gtk_scale_new_with_range (GTK_ORIENTATION_VERTICAL, (gdouble) 0, (gdouble) 1, 0.01);
#line 34 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_ref_sink (_tmp7_);
#line 34 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (self->priv->scale_minim);
#line 34 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->scale_minim = _tmp7_;
#line 35 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp8_ = self->priv->scale_minim;
#line 35 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_set ((GtkWidget*) _tmp8_, "expand", TRUE, NULL);
#line 36 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp9_ = self->priv->scale_minim;
#line 36 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_range_set_inverted ((GtkRange*) _tmp9_, TRUE);
#line 37 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp10_ = self->priv->scale_minim;
#line 37 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_scale_set_draw_value (_tmp10_, FALSE);
#line 38 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp11_ = self->priv->scale_minim;
#line 38 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_signal_connect_object ((GtkRange*) _tmp11_, "value-changed", (GCallback) ___lambda13__gtk_range_value_changed, self, 0);
#line 44 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp12_ = (GtkImage*) gtk_image_new_from_file (CONSTANTS_PKGDATADIR "/icons/symbol_minim.png");
#line 44 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_ref_sink (_tmp12_);
#line 44 "/home/artem/metronome/src/Widgets/Volumes.vala"
	icon_minim = _tmp12_;
#line 46 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp13_ = (GtkScale*) gtk_scale_new_with_range (GTK_ORIENTATION_VERTICAL, (gdouble) 0, (gdouble) 1, 0.01);
#line 46 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_ref_sink (_tmp13_);
#line 46 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (self->priv->scale_crotchet);
#line 46 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->scale_crotchet = _tmp13_;
#line 47 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp14_ = self->priv->scale_crotchet;
#line 47 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_set ((GtkWidget*) _tmp14_, "expand", TRUE, NULL);
#line 48 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp15_ = self->priv->scale_crotchet;
#line 48 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_range_set_inverted ((GtkRange*) _tmp15_, TRUE);
#line 49 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp16_ = self->priv->scale_crotchet;
#line 49 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_scale_set_draw_value (_tmp16_, FALSE);
#line 50 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp17_ = self->priv->scale_crotchet;
#line 50 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_signal_connect_object ((GtkRange*) _tmp17_, "value-changed", (GCallback) ___lambda14__gtk_range_value_changed, self, 0);
#line 56 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp18_ = (GtkImage*) gtk_image_new_from_file (CONSTANTS_PKGDATADIR "/icons/symbol_crotchet.png");
#line 56 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_ref_sink (_tmp18_);
#line 56 "/home/artem/metronome/src/Widgets/Volumes.vala"
	icon_crotchet = _tmp18_;
#line 58 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp19_ = (GtkScale*) gtk_scale_new_with_range (GTK_ORIENTATION_VERTICAL, (gdouble) 0, (gdouble) 1, 0.01);
#line 58 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_ref_sink (_tmp19_);
#line 58 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (self->priv->scale_quaver);
#line 58 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->scale_quaver = _tmp19_;
#line 59 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp20_ = self->priv->scale_quaver;
#line 59 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_set ((GtkWidget*) _tmp20_, "expand", TRUE, NULL);
#line 60 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp21_ = self->priv->scale_quaver;
#line 60 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_range_set_inverted ((GtkRange*) _tmp21_, TRUE);
#line 61 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp22_ = self->priv->scale_quaver;
#line 61 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_scale_set_draw_value (_tmp22_, FALSE);
#line 62 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp23_ = self->priv->scale_quaver;
#line 62 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_signal_connect_object ((GtkRange*) _tmp23_, "value-changed", (GCallback) ___lambda15__gtk_range_value_changed, self, 0);
#line 68 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp24_ = (GtkImage*) gtk_image_new_from_file (CONSTANTS_PKGDATADIR "/icons/symbol-quaver.png");
#line 68 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_ref_sink (_tmp24_);
#line 68 "/home/artem/metronome/src/Widgets/Volumes.vala"
	icon_quaver = _tmp24_;
#line 70 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp25_ = self->priv->scale_semibreve;
#line 70 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp25_, 0, 0, 1, 1);
#line 71 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) icon_semibreve, 0, 1, 1, 1);
#line 72 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp26_ = self->priv->scale_minim;
#line 72 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp26_, 1, 0, 1, 1);
#line 73 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) icon_minim, 1, 1, 1, 1);
#line 74 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp27_ = self->priv->scale_crotchet;
#line 74 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp27_, 2, 0, 1, 1);
#line 75 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) icon_crotchet, 2, 1, 1, 1);
#line 76 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp28_ = self->priv->scale_quaver;
#line 76 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp28_, 3, 0, 1, 1);
#line 77 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) icon_quaver, 3, 1, 1, 1);
#line 15 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (icon_quaver);
#line 15 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (icon_crotchet);
#line 15 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (icon_minim);
#line 15 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (icon_semibreve);
#line 15 "/home/artem/metronome/src/Widgets/Volumes.vala"
	return self;
#line 398 "Volumes.c"
}


MetronomeWidgetsVolumes* metronome_widgets_volumes_new (void) {
#line 15 "/home/artem/metronome/src/Widgets/Volumes.vala"
	return metronome_widgets_volumes_construct (METRONOME_WIDGETS_TYPE_VOLUMES);
#line 405 "Volumes.c"
}


gdouble metronome_widgets_volumes_get_volume_semibreve (MetronomeWidgetsVolumes* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
#line 81 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_return_val_if_fail (self != NULL, 0.0);
#line 81 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->vol_semibreve;
#line 81 "/home/artem/metronome/src/Widgets/Volumes.vala"
	result = _tmp0_;
#line 81 "/home/artem/metronome/src/Widgets/Volumes.vala"
	return result;
#line 420 "Volumes.c"
}


void metronome_widgets_volumes_set_volume_semibreve (MetronomeWidgetsVolumes* self, gdouble value) {
	GtkScale* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
#line 82 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_return_if_fail (self != NULL);
#line 82 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->scale_semibreve;
#line 82 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp1_ = value;
#line 82 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_range_set_value ((GtkRange*) _tmp0_, _tmp1_);
#line 82 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_notify ((GObject *) self, "volume-semibreve");
#line 437 "Volumes.c"
}


gdouble metronome_widgets_volumes_get_volume_minim (MetronomeWidgetsVolumes* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
#line 86 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_return_val_if_fail (self != NULL, 0.0);
#line 86 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->vol_minim;
#line 86 "/home/artem/metronome/src/Widgets/Volumes.vala"
	result = _tmp0_;
#line 86 "/home/artem/metronome/src/Widgets/Volumes.vala"
	return result;
#line 452 "Volumes.c"
}


void metronome_widgets_volumes_set_volume_minim (MetronomeWidgetsVolumes* self, gdouble value) {
	GtkScale* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
#line 87 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_return_if_fail (self != NULL);
#line 87 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->scale_minim;
#line 87 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp1_ = value;
#line 87 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_range_set_value ((GtkRange*) _tmp0_, _tmp1_);
#line 87 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_notify ((GObject *) self, "volume-minim");
#line 469 "Volumes.c"
}


gdouble metronome_widgets_volumes_get_volume_crotchet (MetronomeWidgetsVolumes* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
#line 91 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_return_val_if_fail (self != NULL, 0.0);
#line 91 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->vol_crotchet;
#line 91 "/home/artem/metronome/src/Widgets/Volumes.vala"
	result = _tmp0_;
#line 91 "/home/artem/metronome/src/Widgets/Volumes.vala"
	return result;
#line 484 "Volumes.c"
}


void metronome_widgets_volumes_set_volume_crotchet (MetronomeWidgetsVolumes* self, gdouble value) {
	GtkScale* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
#line 92 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_return_if_fail (self != NULL);
#line 92 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->scale_crotchet;
#line 92 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp1_ = value;
#line 92 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_range_set_value ((GtkRange*) _tmp0_, _tmp1_);
#line 92 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_notify ((GObject *) self, "volume-crotchet");
#line 501 "Volumes.c"
}


gdouble metronome_widgets_volumes_get_volume_quaver (MetronomeWidgetsVolumes* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
#line 96 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_return_val_if_fail (self != NULL, 0.0);
#line 96 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->vol_quaver;
#line 96 "/home/artem/metronome/src/Widgets/Volumes.vala"
	result = _tmp0_;
#line 96 "/home/artem/metronome/src/Widgets/Volumes.vala"
	return result;
#line 516 "Volumes.c"
}


void metronome_widgets_volumes_set_volume_quaver (MetronomeWidgetsVolumes* self, gdouble value) {
	GtkScale* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
#line 97 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_return_if_fail (self != NULL);
#line 97 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp0_ = self->priv->scale_quaver;
#line 97 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_tmp1_ = value;
#line 97 "/home/artem/metronome/src/Widgets/Volumes.vala"
	gtk_range_set_value ((GtkRange*) _tmp0_, _tmp1_);
#line 97 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_notify ((GObject *) self, "volume-quaver");
#line 533 "Volumes.c"
}


static void metronome_widgets_volumes_class_init (MetronomeWidgetsVolumesClass * klass) {
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	metronome_widgets_volumes_parent_class = g_type_class_peek_parent (klass);
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_type_class_add_private (klass, sizeof (MetronomeWidgetsVolumesPrivate));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_metronome_widgets_volumes_get_property;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_metronome_widgets_volumes_set_property;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	G_OBJECT_CLASS (klass)->finalize = metronome_widgets_volumes_finalize;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), METRONOME_WIDGETS_VOLUMES_VOLUME_SEMIBREVE, g_param_spec_double ("volume-semibreve", "volume-semibreve", "volume-semibreve", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), METRONOME_WIDGETS_VOLUMES_VOLUME_MINIM, g_param_spec_double ("volume-minim", "volume-minim", "volume-minim", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), METRONOME_WIDGETS_VOLUMES_VOLUME_CROTCHET, g_param_spec_double ("volume-crotchet", "volume-crotchet", "volume-crotchet", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), METRONOME_WIDGETS_VOLUMES_VOLUME_QUAVER, g_param_spec_double ("volume-quaver", "volume-quaver", "volume-quaver", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 556 "Volumes.c"
}


static void metronome_widgets_volumes_instance_init (MetronomeWidgetsVolumes * self) {
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv = METRONOME_WIDGETS_VOLUMES_GET_PRIVATE (self);
#line 10 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->vol_semibreve = (gdouble) 0;
#line 11 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->vol_minim = (gdouble) 0;
#line 12 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->vol_crotchet = (gdouble) 0;
#line 13 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self->priv->vol_quaver = (gdouble) 0;
#line 571 "Volumes.c"
}


static void metronome_widgets_volumes_finalize (GObject* obj) {
	MetronomeWidgetsVolumes * self;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, METRONOME_WIDGETS_TYPE_VOLUMES, MetronomeWidgetsVolumes);
#line 5 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (self->priv->scale_semibreve);
#line 6 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (self->priv->scale_minim);
#line 7 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (self->priv->scale_crotchet);
#line 8 "/home/artem/metronome/src/Widgets/Volumes.vala"
	_g_object_unref0 (self->priv->scale_quaver);
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	G_OBJECT_CLASS (metronome_widgets_volumes_parent_class)->finalize (obj);
#line 589 "Volumes.c"
}


GType metronome_widgets_volumes_get_type (void) {
	static volatile gsize metronome_widgets_volumes_type_id__volatile = 0;
	if (g_once_init_enter (&metronome_widgets_volumes_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MetronomeWidgetsVolumesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) metronome_widgets_volumes_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MetronomeWidgetsVolumes), 0, (GInstanceInitFunc) metronome_widgets_volumes_instance_init, NULL };
		GType metronome_widgets_volumes_type_id;
		metronome_widgets_volumes_type_id = g_type_register_static (gtk_grid_get_type (), "MetronomeWidgetsVolumes", &g_define_type_info, 0);
		g_once_init_leave (&metronome_widgets_volumes_type_id__volatile, metronome_widgets_volumes_type_id);
	}
	return metronome_widgets_volumes_type_id__volatile;
}


static void _vala_metronome_widgets_volumes_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	MetronomeWidgetsVolumes * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, METRONOME_WIDGETS_TYPE_VOLUMES, MetronomeWidgetsVolumes);
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	switch (property_id) {
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		case METRONOME_WIDGETS_VOLUMES_VOLUME_SEMIBREVE:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		g_value_set_double (value, metronome_widgets_volumes_get_volume_semibreve (self));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		case METRONOME_WIDGETS_VOLUMES_VOLUME_MINIM:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		g_value_set_double (value, metronome_widgets_volumes_get_volume_minim (self));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		case METRONOME_WIDGETS_VOLUMES_VOLUME_CROTCHET:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		g_value_set_double (value, metronome_widgets_volumes_get_volume_crotchet (self));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		case METRONOME_WIDGETS_VOLUMES_VOLUME_QUAVER:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		g_value_set_double (value, metronome_widgets_volumes_get_volume_quaver (self));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 634 "Volumes.c"
		default:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 640 "Volumes.c"
	}
}


static void _vala_metronome_widgets_volumes_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	MetronomeWidgetsVolumes * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, METRONOME_WIDGETS_TYPE_VOLUMES, MetronomeWidgetsVolumes);
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
	switch (property_id) {
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		case METRONOME_WIDGETS_VOLUMES_VOLUME_SEMIBREVE:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		metronome_widgets_volumes_set_volume_semibreve (self, g_value_get_double (value));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		case METRONOME_WIDGETS_VOLUMES_VOLUME_MINIM:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		metronome_widgets_volumes_set_volume_minim (self, g_value_get_double (value));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		case METRONOME_WIDGETS_VOLUMES_VOLUME_CROTCHET:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		metronome_widgets_volumes_set_volume_crotchet (self, g_value_get_double (value));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		case METRONOME_WIDGETS_VOLUMES_VOLUME_QUAVER:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		metronome_widgets_volumes_set_volume_quaver (self, g_value_get_double (value));
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 674 "Volumes.c"
		default:
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 3 "/home/artem/metronome/src/Widgets/Volumes.vala"
		break;
#line 680 "Volumes.c"
	}
}



